LOGBOOK.LS     Robot Name ROBOT 31-AUG-26 12:49:26  

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Operation        
========================================
FILE 'UPDTLOG.LS' is saved             
31-AUG-26 12:49 :26
========================================
FILE 'IOSTATUS.CM' is saved            
31-AUG-26 12:49 :26
========================================
FILE 'HIST.LS' is saved                
31-AUG-26 12:49 :24
========================================
FILE 'BACKDATE.DT' is saved            
31-AUG-26 12:49 :24
========================================
FILE 'ERREXT.LS' is saved              
31-AUG-26 12:49 :24
========================================
FILE 'ERRCOMM.LS' is saved             
31-AUG-26 12:49 :24
========================================
FILE 'ERRHIST.LS' is saved             
31-AUG-26 12:49 :24
========================================
FILE 'ERRCURR.LS' is saved             
31-AUG-26 12:49 :24
========================================
FILE 'ERRPWD.LS' is saved              
31-AUG-26 12:49 :24
========================================
FILE 'ERRAPP.LS' is saved              
31-AUG-26 12:49 :24
========================================
FILE 'ERRSYS.LS' is saved              
31-AUG-26 12:49 :24
========================================
FILE 'ERRMOT.LS' is saved              
31-AUG-26 12:49 :24
========================================
FILE 'ERRACT.LS' is saved              
31-AUG-26 12:49 :24
========================================
FILE 'ERRALL.LS' is saved              
31-AUG-26 12:49 :24
========================================
FILE 'TPEINS.XML' is saved             
31-AUG-26 12:49 :24
========================================
FILE 'PANEL4.DT' is saved              
31-AUG-26 12:49 :24
========================================
FILE 'PANEL4.STM' is saved             
31-AUG-26 12:49 :24
========================================
FILE 'PANEL3.DT' is saved              
31-AUG-26 12:49 :24
========================================
FILE 'PANEL3.STM' is saved             
31-AUG-26 12:49 :24
========================================
FILE 'PANEL2.DT' is saved              
31-AUG-26 12:49 :22
========================================
FILE 'PANEL2.STM' is saved             
31-AUG-26 12:49 :22
========================================
FILE 'PANEL1.DT' is saved              
31-AUG-26 12:49 :22
========================================
FILE 'PANEL1.STM' is saved             
31-AUG-26 12:49 :22
========================================
FILE 'SPACER.GIF' is saved             
31-AUG-26 12:49 :22
========================================
FILE 'PBUTTON.GIF' is saved            
31-AUG-26 12:49 :22
========================================
FILE 'NBUTTON.GIF' is saved            
31-AUG-26 12:49 :22
========================================
FILE 'XXXXXLED.GIF' is saved           
31-AUG-26 12:49 :22
========================================
FILE 'REDLED.GIF' is saved             
31-AUG-26 12:49 :22
========================================
FILE 'GREENLED.GIF' is saved           
31-AUG-26 12:49 :22
========================================
FILE 'DARKLED.GIF' is saved            
31-AUG-26 12:49 :22
========================================
FILE 'AMBERLED.GIF' is saved           
31-AUG-26 12:49 :22
========================================
FILE 'RESTART.STM' is saved            
31-AUG-26 12:49 :22
========================================
FILE 'PANEL4.STM' is saved             
31-AUG-26 12:49 :22
========================================
FILE 'PANEL3.STM' is saved             
31-AUG-26 12:49 :22
========================================
FILE 'PANEL2.STM' is saved             
31-AUG-26 12:49 :22
========================================
FILE 'PANEL1.STM' is saved             
31-AUG-26 12:49 :22
========================================
FILE 'SET_BLOW_POS.PC' is saved        
31-AUG-26 12:49 :22
========================================
FILE 'OPTIMIZE_POS.PC' is saved        
31-AUG-26 12:49 :22
========================================
FILE 'VC_MOVE.VR' is saved             
31-AUG-26 12:49 :22
========================================
FILE 'VCMRINIT.VR' is saved            
31-AUG-26 12:49 :22
========================================
FILE 'TPSNAP.VR' is saved              
31-AUG-26 12:49 :22
========================================
FILE 'SWIUPDT.VR' is saved             
31-AUG-26 12:49 :22
========================================
FILE 'SET_BLOW_POS.VR' is saved        
31-AUG-26 12:49 :22
========================================
FILE 'PNIO_ALM.VR' is saved            
31-AUG-26 12:49 :22
========================================
FILE 'OPTIMIZE_POS.VR' is saved        
31-AUG-26 12:49 :22
========================================
FILE 'MNUZVHF.VR' is saved             
31-AUG-26 12:49 :22
========================================
FILE 'KLACTION.VR' is saved            
31-AUG-26 12:49 :20
========================================
FILE 'IRC_STLABEL.VR' is saved         
31-AUG-26 12:49 :20
========================================
FILE 'IRC_STATUS.VR' is saved          
31-AUG-26 12:49 :20
========================================
FILE 'IRC_MSG.VR' is saved             
31-AUG-26 12:49 :20
========================================
FILE 'IRC_COUNTER.VR' is saved         
31-AUG-26 12:49 :20
========================================
FILE 'HTTPKCL.VR' is saved             
31-AUG-26 12:49 :20
========================================
FILE 'HTCOLREC.VR' is saved            
31-AUG-26 12:49 :20
========================================
FILE 'GEMDATA.VR' is saved             
31-AUG-26 12:49 :20
========================================
FILE 'COMSET.VR' is saved              
31-AUG-26 12:49 :20
========================================
FILE 'CBPARAM.VR' is saved             
31-AUG-26 12:49 :20
========================================
FILE 'BICSETUP.VR' is saved            
31-AUG-26 12:49 :20
========================================
FILE 'AAVMMAIN.VR' is saved            
31-AUG-26 12:49 :20
========================================
FILE 'AAVMFREEPOS.VR' is saved         
31-AUG-26 12:49 :20
========================================
FILE 'SYSPASS.SV' is saved             
31-AUG-26 12:49 :20
========================================
FILE 'SYSHOST.SV' is saved             
31-AUG-26 12:49 :20
========================================
FILE 'SYSFSAC.SV' is saved             
31-AUG-26 12:49 :20
========================================
FILE 'SYSEIP.SV' is saved              
31-AUG-26 12:49 :20
========================================
FILE 'FLEXUIF.XML' is saved            
31-AUG-26 12:49 :18
========================================
FILE 'LR2D.DT' is saved                
31-AUG-26 12:49 :18
========================================
FILE 'CELLIO.SV' is saved              
31-AUG-26 12:49 :18
========================================
FILE 'DCSIOC.SV' is saved              
31-AUG-26 12:49 :18
========================================
FILE 'SYSPNSF.SV' is saved             
31-AUG-26 12:49 :16
========================================
FILE 'PNIOG2.SV' is saved              
31-AUG-26 12:49 :16
========================================
FILE 'MIXLOGIC.SV' is saved            
31-AUG-26 12:49 :16
========================================
FILE 'SECLOG.DG' is saved              
31-AUG-26 12:49 :16
========================================
FILE 'EMAIL.DG' is saved               
31-AUG-26 12:49 :16
========================================
FILE 'POSREG.VR' is saved              
31-AUG-26 12:49 :16
========================================
FILE 'VARCHG.XML' is saved             
31-AUG-26 12:49 :16
========================================
FILE 'RCMCFG.XML' is saved             
31-AUG-26 12:49 :16
========================================
FILE 'SYSUIF.SV' is saved              
31-AUG-26 12:49 :16
========================================
FILE 'STRREG.VR' is saved              
31-AUG-26 12:49 :16
========================================
FILE 'SYSFRAME.SV' is saved            
31-AUG-26 12:49 :16
========================================
FILE 'DIOCFGSV.IO' is saved            
31-AUG-26 12:49 :16
========================================
FILE 'SYSMACRO.SV' is saved            
31-AUG-26 12:49 :16
========================================
FILE 'SYSMAST.SV' is saved             
31-AUG-26 12:49 :16
========================================
FILE 'SYSSERVO.SV' is saved            
31-AUG-26 12:49 :16
========================================
FILE 'SYSVARS.SV' is saved             
31-AUG-26 12:49 :14
========================================
FILE 'NUMREG.VR' is saved              
31-AUG-26 12:49 :14
========================================
FILE 'FRAMEVAR.VR' is saved            
31-AUG-26 12:49 :14
========================================
F4(  YES   ) is pressed                
31-AUG-26 12:49 :10
--Screen image--------------------------
SRVO-003 Deadman switch released                                                
PLACE_VICE1_T2    LINE 0    \T1\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
FILE\\\\\\\\\\\\\\\\\\\\\\\\\\       0 1                                        
UD1:\ROBOT\*.*                    1/33                                          
\\\1\..\\\\\\\\(Up\one\level)\\\\\\\\\\\ <DIR>                                  
   2 *       *   (all files)                                                    
   3 *       KL  (all KAREL source)                                             
   4 *       CF  (all command files)                                            
   5 *       TX  (all text files)                                               
   6 *       LS  (all KAREL listings)                                           
   7 *       DT  (all KAREL data files)                                         
   8 *       PC  (all KAREL p-code)                                             
   9 *       TP  (all TP programs)                                              
  10 *       MN  (all MN programs)                                              
  11 *       VR  (all variable files)                                           
  12 *       SV  (all system files)                                             
  13 *       IO  (I/O config data)                                              
  14 *       DF  (all DEFAULT files)                                            
  15 *       ML  (all part model files)                                         
  16 *       BMP  (all bit-map images)                                          
  17 *       PMC  (all PMC files)                                               
  18 *       VA  (all Variable Listings)                                        
  19 *       DG  (all Diagnostic files)                                         
  20 *       VD  (all Vision VD files)                                          
Delete UD1:\ROBOT\ and backup all files?                                        
                          YES      NO                                           
========================================
F4(  YES   ) is pressed                
31-AUG-26 12:49 :08
--Screen image--------------------------
SRVO-003 Deadman switch released                                                
PLACE_VICE1_T2    LINE 0    \T1\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
FILE\\\\\\\\\\\\\\\\\\\\\\\\\\       0 1                                        
UD1:\ROBOT\*.*                    1/33                                          
\\\1\..\\\\\\\\(Up\one\level)\\\\\\\\\\\ <DIR>                                  
   2 *       *   (all files)                                                    
   3 *       KL  (all KAREL source)                                             
   4 *       CF  (all command files)                                            
   5 *       TX  (all text files)                                               
   6 *       LS  (all KAREL listings)                                           
   7 *       DT  (all KAREL data files)                                         
   8 *       PC  (all KAREL p-code)                                             
   9 *       TP  (all TP programs)                                              
  10 *       MN  (all MN programs)                                              
  11 *       VR  (all variable files)                                           
  12 *       SV  (all system files)                                             
  13 *       IO  (I/O config data)                                              
  14 *       DF  (all DEFAULT files)                                            
  15 *       ML  (all part model files)                                         
  16 *       BMP  (all bit-map images)                                          
  17 *       PMC  (all PMC files)                                               
  18 *       VA  (all Variable Listings)                                        
  19 *       DG  (all Diagnostic files)                                         
  20 *       VD  (all Vision VD files)                                          
Delete UD1:\ROBOT\ before backup files?                                         
                          YES      NO                                           
========================================
'All of above' is selected             
31-AUG-26 12:48 :58
--Screen image--------------------------
SRVO-003 Deadman switch released                                                
PLACE_VICE1_T2    LINE 0    \T1\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
FILE\\\\\\\\\\\\\\\\\\\\\\\\\\       0 1                                        
UD1:\ROBOT\*.*                    1/33                                          
\\\1\..\\\\\\\\(Up\one\level)\\\\\\\\\\\ <DIR>                                  
   2 *       *   (all files)                                                    
   3 *       KL  (all KAREL source)                                             
   4 *       CF  (all command files)                                            
   5 *       TX  (all text files)                                               
   6 *       LS  (all KAREL listings)                                           
   7 *       DT  (all KAREL data files)                                         
   8 *       PC  (all KAREL p-code)                                             
   9 *       TP  (all TP programs)                                              
  10 *       MN  (all MN programs)                                              
  11 *       VR  (all variable files)                                           
  12 *       SV  (all system files)                                             
  13 *       IO  (I/O config data)                                              
  14 *       DF  (all DEFAULT files)                                            
  15 *       ML  (all part model files)                                         
  16 *       BMP  (all bit-map images)                                          
  17 *       PMC  (all PMC files)                                               
  18 *       VA  (all Variable Listings)                                        
  19 *       DG  (all Diagnostic files)                                         
  20 *       VD  (all Vision VD files)                                          
                                                                                
[ TYPE ] [ DIR ]  LOAD  |BACKUP|[UTIL ]>                                        
========================================
F4([BACKUP]) is pressed                
31-AUG-26 12:48 :32
--Screen image--------------------------
SRVO-003 Deadman switch released                                                
PLACE_VICE1_T2    LINE 0    \T1\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
FILE\\\\\\\\\\\\\\\\\\\\\\\\\\       0 1                                        
UD1:\ROBOT\*.*                    1/33                                          
\\\1\..\\\\\\\\(Up\one\level)\\\\\\\\\\\ <DIR>                                  
   2 *       *   (all files)                                                    
   3 *       KL  (all KAREL source)                                             
   4 *       CF  (all command files)                                            
   5 *       TX  (all text files)                                               
   6 *       LS  (all KAREL listings)                                           
   7 *       DT  (all KAREL data files)                                         
   8 *       PC  (all KAREL p-code)                                             
   9 *       TP  (all TP programs)                                              
  10 *       MN  (all MN programs)                                              
  11 *       VR  (all variable files)                                           
  12 *       SV  (all system files)                                             
  13 *       IO  (I/O config data)                                              
  14 *       DF  (all DEFAULT files)                                            
  15 *       ML  (all part model files)                                         
  16 *       BMP  (all bit-map images)                                          
  17 *       PMC  (all PMC files)                                               
  18 *       VA  (all Variable Listings)                                        
  19 *       DG  (all Diagnostic files)                                         
  20 *       VD  (all Vision VD files)                                          
                                                                                
[ TYPE ] [ DIR ]  LOAD  [BACKUP][UTIL ]>                                        
========================================
robot is entered                       
31-AUG-26 12:47 :26
--Screen image--------------------------
SRVO-003 Deadman switch released                                                
PLACE_VICE1_T2    LINE 0    \T1\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
FILE\\\\\\\\\\\\\\\\\\\\\\\\\\       0 1                                        
UD1:\*.*                          1/32                                          
\\\1\*\\\\\\\*\\\(all\files)\\\\\\\\\\\\                                        
   2 *       KL  (all KAREL source)                                             
   3 *       CF  (all command files)                                            
   4 *       TX  (all text files)                                               
   5 *       LS  (all KAREL listings)                                           
   6 *       DT  (all KAREL data files)                                         
   7 *       PC  (all KAREL p-code)                                             
   8 *       TP  (all TP programs)                                              
   9 *       MN  (all MN programs)                                              
  10 *       VR  (all variable files)                                           
  11 *       SV  (all system files)                                             
  12 *       IO  (I/O config data)                                              
  13 *       DF  (all DEFAULT files)                                            
  14 *       ML  (all part model files)                                         
  15 *       BMP  (all bit-map images)                                          
  16 *       PMC  (all PMC files)                                               
  17 *       VA  (all Variable Listings)                                        
  18 *       DG  (all Diagnostic files)                                         
  19 *       VD  (all Vision VD files)                                          
  20 *       IBG  (all IBG files)                                               
Directory name:                                                                 
   PRG    MAIN     SUB    TEST                                                  
========================================
'Make DIR' is selected                 
31-AUG-26 12:47 :12
--Screen image--------------------------
SRVO-003 Deadman switch released                                                
PLACE_VICE1_T2    LINE 0    \T1\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
FILE\\\\\\\\\\\\\\\\\\\\\\\\\\       0 1                                        
UD1:\*.*                          1/32                                          
\\\1\*\\\\\\\*\\\(all\files)\\\\\\\\\\\\                                        
   2 *       KL  (all KAREL source)                                             
   3 *       CF  (all command files)                                            
   4 *       TX  (all text files)                                               
   5 *       LS  (all KAREL listings)                                           
   6 *       DT  (all KAREL data files)                                         
   7 *       PC  (all KAREL p-code)                                             
   8 *       TP  (all TP programs)                                              
   9 *       MN  (all MN programs)                                              
  10 *       VR  (all variable files)                                           
  11 *       SV  (all system files)                                             
  12 *       IO  (I/O config data)                                              
  13 *       DF  (all DEFAULT files)                                            
  14 *       ML  (all part model files)                                         
  15 *       BMP  (all bit-map images)                                          
  16 *       PMC  (all PMC files)                                               
  17 *       VA  (all Variable Listings)                                        
  18 *       DG  (all Diagnostic files)                                         
  19 *       VD  (all Vision VD files)                                          
  20 *       IBG  (all IBG files)                                               
                                                                                
[ TYPE ] [ DIR ]  LOAD  [BACKUP]|UTIL |>                                        
========================================
F5([UTIL ]>) is pressed                
31-AUG-26 12:47 :08
--Screen image--------------------------
SRVO-003 Deadman switch released                                                
PLACE_VICE1_T2    LINE 0    \T1\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
FILE\\\\\\\\\\\\\\\\\\\\\\\\\\       0 1                                        
UD1:\*.*                          1/32                                          
\\\1\*\\\\\\\*\\\(all\files)\\\\\\\\\\\\                                        
   2 *       KL  (all KAREL source)                                             
   3 *       CF  (all command files)                                            
   4 *       TX  (all text files)                                               
   5 *       LS  (all KAREL listings)                                           
   6 *       DT  (all KAREL data files)                                         
   7 *       PC  (all KAREL p-code)                                             
   8 *       TP  (all TP programs)                                              
   9 *       MN  (all MN programs)                                              
  10 *       VR  (all variable files)                                           
  11 *       SV  (all system files)                                             
  12 *       IO  (I/O config data)                                              
  13 *       DF  (all DEFAULT files)                                            
  14 *       ML  (all part model files)                                         
  15 *       BMP  (all bit-map images)                                          
  16 *       PMC  (all PMC files)                                               
  17 *       VA  (all Variable Listings)                                        
  18 *       DG  (all Diagnostic files)                                         
  19 *       VD  (all Vision VD files)                                          
  20 *       IBG  (all IBG files)                                               
                                                                                
[ TYPE ] [ DIR ]  LOAD  [BACKUP][UTIL ]>                                        
========================================
ENTER is pressed                       
31-AUG-26 12:47 :06
========================================
SRVO-003 Deadman switch released       
                                       
                                       
SERVO                         00110110 
31-AUG-26 12:47 :02
========================================
R E S E T                              
                                       
                              00000000 
31-AUG-26 12:47 :02
========================================
RESET is pressed                       
31-AUG-26 12:47 :02
========================================
SRVO-003 Deadman switch released       
                                       
                                       
SERVO                         00110110 
31-AUG-26 12:47 :02
========================================
R E S E T                              
                                       
                              00000000 
31-AUG-26 12:47 :02
========================================
SRVO-003 Deadman switch released       
                                       
                                       
SERVO                         00110110 
31-AUG-26 12:47 :02
========================================
RESET is pressed                       
31-AUG-26 12:47 :02
========================================
R E S E T                              
                                       
                              00000000 
31-AUG-26 12:47 :02
========================================
RESET is pressed                       
31-AUG-26 12:47 :02
========================================
ENTER is pressed                       
31-AUG-26 12:46 :52
========================================
'USB Disk (UD1:)' is selected          
31-AUG-26 12:44 :42
--Screen image--------------------------
TPIF-149 Must complete operation first                                          
PLACE_VICE1_T2    LINE 0    \T1\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
FILE\\\\\\\\\\\\\\\\\\\\\\\\\\       0 1                                        
UD1:\JJ\*.*                       1/33                                          
\\\1\..\\\\\\\\(Up\one\level)\\\\\\\\\\\ <DIR>                                  
   2 *       *   (all files)                                                    
   3 *       KL  (all KAREL source)                                             
   4 *       CF  (all command files)                                            
   5 *       TX  (all text files)                                               
   6 *       LS  (all KAREL listings)                                           
   7 *       DT  (all KAREL data files)                                         
   8 *       PC  (all KAREL p-code)                                             
   9 *       TP  (all TP programs)                                              
  10 *       MN  (all MN programs)                                              
  11 *       VR  (all variable files)                                           
  12 *       SV  (all system files)                                             
  13 *       IO  (I/O config data)                                              
  14 *       DF  (all DEFAULT files)                                            
  15 *       ML  (all part model files)                                         
  16 *       BMP  (all bit-map images)                                          
  17 *       PMC  (all PMC files)                                               
  18 *       VA  (all Variable Listings)                                        
  19 *       DG  (all Diagnostic files)                                         
  20 *       VD  (all Vision VD files)                                          
Press DIR to generate directory                                                 
[ TYPE ] [ DIR ]  LOAD  [BACKUP][UTIL ]>                                        
========================================
'Set Device' is selected               
31-AUG-26 12:44 :32
--Screen image--------------------------
TPIF-149 Must complete operation first                                          
PLACE_VICE1_T2    LINE 0    \T1\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
FILE\\\\\\\\\\\\\\\\\\\\\\\\\\       0 1                                        
UD1:\JJ\*.*                       1/33                                          
\\\1\..\\\\\\\\(Up\one\level)\\\\\\\\\\\ <DIR>                                  
   2 *       *   (all files)                                                    
   3 *       KL  (all KAREL source)                                             
   4 *       CF  (all command files)                                            
   5 *       TX  (all text files)                                               
   6 *       LS  (all KAREL listings)                                           
   7 *       DT  (all KAREL data files)                                         
   8 *       PC  (all KAREL p-code)                                             
   9 *       TP  (all TP programs)                                              
  10 *       MN  (all MN programs)                                              
  11 *       VR  (all variable files)                                           
  12 *       SV  (all system files)                                             
  13 *       IO  (I/O config data)                                              
  14 *       DF  (all DEFAULT files)                                            
  15 *       ML  (all part model files)                                         
  16 *       BMP  (all bit-map images)                                          
  17 *       PMC  (all PMC files)                                               
  18 *       VA  (all Variable Listings)                                        
  19 *       DG  (all Diagnostic files)                                         
  20 *       VD  (all Vision VD files)                                          
Press DIR to generate directory                                                 
[ TYPE ] [ DIR ]  LOAD  [BACKUP]|UTIL |>                                        
========================================
F5([UTIL ]>) is pressed                
31-AUG-26 12:44 :30
--Screen image--------------------------
TPIF-149 Must complete operation first                                          
PLACE_VICE1_T2    LINE 0    \T1\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
FILE\\\\\\\\\\\\\\\\\\\\\\\\\\       0 1                                        
UD1:\JJ\*.*                       1/33                                          
\\\1\..\\\\\\\\(Up\one\level)\\\\\\\\\\\ <DIR>                                  
   2 *       *   (all files)                                                    
   3 *       KL  (all KAREL source)                                             
   4 *       CF  (all command files)                                            
   5 *       TX  (all text files)                                               
   6 *       LS  (all KAREL listings)                                           
   7 *       DT  (all KAREL data files)                                         
   8 *       PC  (all KAREL p-code)                                             
   9 *       TP  (all TP programs)                                              
  10 *       MN  (all MN programs)                                              
  11 *       VR  (all variable files)                                           
  12 *       SV  (all system files)                                             
  13 *       IO  (I/O config data)                                              
  14 *       DF  (all DEFAULT files)                                            
  15 *       ML  (all part model files)                                         
  16 *       BMP  (all bit-map images)                                          
  17 *       PMC  (all PMC files)                                               
  18 *       VA  (all Variable Listings)                                        
  19 *       DG  (all Diagnostic files)                                         
  20 *       VD  (all Vision VD files)                                          
Press DIR to generate directory                                                 
[ TYPE ] [ DIR ]  LOAD  [BACKUP][UTIL ]>                                        
========================================
ENTER is pressed                       
31-AUG-26 12:44 :20
========================================
 is entered                            
31-AUG-26 12:44 :16
--Screen image--------------------------
TPIF-149 Must complete operation first                                          
PLACE_VICE1_T2    LINE 0    \T1\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
FILE\\\\\\\\\\\\\\\\\\\\\\\\\\       0 1                                        
UD1:\JJ\*.*                       1/33                                          
\\\1\..\\\\\\\\(Up\one\level)\\\\\\\\\\\ <DIR>                                  
   2 *       *   (all files)                                                    
   3 *       KL  (all KAREL source)                                             
   4 *       CF  (all command files)                                            
   5 *       TX  (all text files)                                               
   6 *       LS  (all KAREL listings)                                           
   7 *       DT  (all KAREL data files)                                         
   8 *       PC  (all KAREL p-code)                                             
   9 *       TP  (all TP programs)                                              
  10 *       MN  (all MN programs)                                              
  11 *       VR  (all variable files)                                           
  12 *       SV  (all system files)                                             
  13 *       IO  (I/O config data)                                              
  14 *       DF  (all DEFAULT files)                                            
  15 *       ML  (all part model files)                                         
  16 *       BMP  (all bit-map images)                                          
  17 *       PMC  (all PMC files)                                               
  18 *       VA  (all Variable Listings)                                        
  19 *       DG  (all Diagnostic files)                                         
  20 *       VD  (all Vision VD files)                                          
Directory name:                                                                 
   PRG    MAIN     SUB    TEST                                                  
========================================
'Make DIR' is selected                 
31-AUG-26 12:44 :14
--Screen image--------------------------
TPIF-149 Must complete operation first                                          
PLACE_VICE1_T2    LINE 0    \T1\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
FILE\\\\\\\\\\\\\\\\\\\\\\\\\\       0 1                                        
UD1:\JJ\*.*                       1/33                                          
\\\1\..\\\\\\\\(Up\one\level)\\\\\\\\\\\ <DIR>                                  
   2 *       *   (all files)                                                    
   3 *       KL  (all KAREL source)                                             
   4 *       CF  (all command files)                                            
   5 *       TX  (all text files)                                               
   6 *       LS  (all KAREL listings)                                           
   7 *       DT  (all KAREL data files)                                         
   8 *       PC  (all KAREL p-code)                                             
   9 *       TP  (all TP programs)                                              
  10 *       MN  (all MN programs)                                              
  11 *       VR  (all variable files)                                           
  12 *       SV  (all system files)                                             
  13 *       IO  (I/O config data)                                              
  14 *       DF  (all DEFAULT files)                                            
  15 *       ML  (all part model files)                                         
  16 *       BMP  (all bit-map images)                                          
  17 *       PMC  (all PMC files)                                               
  18 *       VA  (all Variable Listings)                                        
  19 *       DG  (all Diagnostic files)                                         
  20 *       VD  (all Vision VD files)                                          
                                                                                
[ TYPE ] [ DIR ]  LOAD  [BACKUP]|UTIL |>                                        
========================================
F5([UTIL ]>) is pressed                
31-AUG-26 12:44 :12
--Screen image--------------------------
TPIF-149 Must complete operation first                                          
PLACE_VICE1_T2    LINE 0    \T1\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
FILE\\\\\\\\\\\\\\\\\\\\\\\\\\       0 1                                        
UD1:\JJ\*.*                       1/33                                          
\\\1\..\\\\\\\\(Up\one\level)\\\\\\\\\\\ <DIR>                                  
   2 *       *   (all files)                                                    
   3 *       KL  (all KAREL source)                                             
   4 *       CF  (all command files)                                            
   5 *       TX  (all text files)                                               
   6 *       LS  (all KAREL listings)                                           
   7 *       DT  (all KAREL data files)                                         
   8 *       PC  (all KAREL p-code)                                             
   9 *       TP  (all TP programs)                                              
  10 *       MN  (all MN programs)                                              
  11 *       VR  (all variable files)                                           
  12 *       SV  (all system files)                                             
  13 *       IO  (I/O config data)                                              
  14 *       DF  (all DEFAULT files)                                            
  15 *       ML  (all part model files)                                         
  16 *       BMP  (all bit-map images)                                          
  17 *       PMC  (all PMC files)                                               
  18 *       VA  (all Variable Listings)                                        
  19 *       DG  (all Diagnostic files)                                         
  20 *       VD  (all Vision VD files)                                          
                                                                                
[ TYPE ] [ DIR ]  LOAD  [BACKUP][UTIL ]>                                        
========================================
jj is entered                          
31-AUG-26 12:43 :30
--Screen image--------------------------
TPIF-149 Must complete operation first                                          
PLACE_VICE1_T2    LINE 0    \T1\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
FILE\\\\\\\\\\\\\\\\\\\\\\\\\\       0 1                                        
UD1:\*.*                          1/32                                          
\\\1\*\\\\\\\*\\\(all\files)\\\\\\\\\\\\                                        
   2 *       KL  (all KAREL source)                                             
   3 *       CF  (all command files)                                            
   4 *       TX  (all text files)                                               
   5 *       LS  (all KAREL listings)                                           
   6 *       DT  (all KAREL data files)                                         
   7 *       PC  (all KAREL p-code)                                             
   8 *       TP  (all TP programs)                                              
   9 *       MN  (all MN programs)                                              
  10 *       VR  (all variable files)                                           
  11 *       SV  (all system files)                                             
  12 *       IO  (I/O config data)                                              
  13 *       DF  (all DEFAULT files)                                            
  14 *       ML  (all part model files)                                         
  15 *       BMP  (all bit-map images)                                          
  16 *       PMC  (all PMC files)                                               
  17 *       VA  (all Variable Listings)                                        
  18 *       DG  (all Diagnostic files)                                         
  19 *       VD  (all Vision VD files)                                          
  20 *       IBG  (all IBG files)                                               
Directory name:                                                                 
   PRG    MAIN     SUB    TEST                                                  
========================================
'Make DIR' is selected                 
31-AUG-26 12:43 :26
--Screen image--------------------------
TPIF-149 Must complete operation first                                          
PLACE_VICE1_T2    LINE 0    \T1\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
FILE\\\\\\\\\\\\\\\\\\\\\\\\\\       0 1                                        
UD1:\*.*                          1/32                                          
\\\1\*\\\\\\\*\\\(all\files)\\\\\\\\\\\\                                        
   2 *       KL  (all KAREL source)                                             
   3 *       CF  (all command files)                                            
   4 *       TX  (all text files)                                               
   5 *       LS  (all KAREL listings)                                           
   6 *       DT  (all KAREL data files)                                         
   7 *       PC  (all KAREL p-code)                                             
   8 *       TP  (all TP programs)                                              
   9 *       MN  (all MN programs)                                              
  10 *       VR  (all variable files)                                           
  11 *       SV  (all system files)                                             
  12 *       IO  (I/O config data)                                              
  13 *       DF  (all DEFAULT files)                                            
  14 *       ML  (all part model files)                                         
  15 *       BMP  (all bit-map images)                                          
  16 *       PMC  (all PMC files)                                               
  17 *       VA  (all Variable Listings)                                        
  18 *       DG  (all Diagnostic files)                                         
  19 *       VD  (all Vision VD files)                                          
  20 *       IBG  (all IBG files)                                               
Press DIR to generate directory                                                 
[ TYPE ] [ DIR ]  LOAD  [BACKUP]|UTIL |>                                        
========================================
F5([UTIL ]>) is pressed                
31-AUG-26 12:43 :24
--Screen image--------------------------
TPIF-149 Must complete operation first                                          
PLACE_VICE1_T2    LINE 0    \T1\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
FILE\\\\\\\\\\\\\\\\\\\\\\\\\\       0 1                                        
UD1:\*.*                          1/32                                          
\\\1\*\\\\\\\*\\\(all\files)\\\\\\\\\\\\                                        
   2 *       KL  (all KAREL source)                                             
   3 *       CF  (all command files)                                            
   4 *       TX  (all text files)                                               
   5 *       LS  (all KAREL listings)                                           
   6 *       DT  (all KAREL data files)                                         
   7 *       PC  (all KAREL p-code)                                             
   8 *       TP  (all TP programs)                                              
   9 *       MN  (all MN programs)                                              
  10 *       VR  (all variable files)                                           
  11 *       SV  (all system files)                                             
  12 *       IO  (I/O config data)                                              
  13 *       DF  (all DEFAULT files)                                            
  14 *       ML  (all part model files)                                         
  15 *       BMP  (all bit-map images)                                          
  16 *       PMC  (all PMC files)                                               
  17 *       VA  (all Variable Listings)                                        
  18 *       DG  (all Diagnostic files)                                         
  19 *       VD  (all Vision VD files)                                          
  20 *       IBG  (all IBG files)                                               
Press DIR to generate directory                                                 
[ TYPE ] [ DIR ]  LOAD  [BACKUP][UTIL ]>                                        
========================================
'USB Disk (UD1:)' is selected          
31-AUG-26 12:43 :22
--Screen image--------------------------
TPIF-149 Must complete operation first                                          
PLACE_VICE1_T2    LINE 0    \T1\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
FILE\\\\\\\\\\\\\\\\\\\\\\\\\\       0 1                                        
UT1:\*.*                          1/32                                          
\\\1\*\\\\\\\*\\\(all\files)\\\\\\\\\\\\                                        
   2 *       KL  (all KAREL source)                                             
   3 *       CF  (all command files)                                            
   4 *       TX  (all text files)                                               
   5 *       LS  (all KAREL listings)                                           
   6 *       DT  (all KAREL data files)                                         
   7 *       PC  (all KAREL p-code)                                             
   8 *       TP  (all TP programs)                                              
   9 *       MN  (all MN programs)                                              
  10 *       VR  (all variable files)                                           
  11 *       SV  (all system files)                                             
  12 *       IO  (I/O config data)                                              
  13 *       DF  (all DEFAULT files)                                            
  14 *       ML  (all part model files)                                         
  15 *       BMP  (all bit-map images)                                          
  16 *       PMC  (all PMC files)                                               
  17 *       VA  (all Variable Listings)                                        
  18 *       DG  (all Diagnostic files)                                         
  19 *       VD  (all Vision VD files)                                          
  20 *       IBG  (all IBG files)                                               
Press DIR to generate directory                                                 
[ TYPE ] [ DIR ]  LOAD  [BACKUP][UTIL ]>                                        
========================================
'Set Device' is selected               
31-AUG-26 12:43 :18
--Screen image--------------------------
TPIF-149 Must complete operation first                                          
PLACE_VICE1_T2    LINE 0    \T1\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
FILE\\\\\\\\\\\\\\\\\\\\\\\\\\       0 1                                        
UT1:\*.*                          1/32                                          
\\\1\*\\\\\\\*\\\(all\files)\\\\\\\\\\\\                                        
   2 *       KL  (all KAREL source)                                             
   3 *       CF  (all command files)                                            
   4 *       TX  (all text files)                                               
   5 *       LS  (all KAREL listings)                                           
   6 *       DT  (all KAREL data files)                                         
   7 *       PC  (all KAREL p-code)                                             
   8 *       TP  (all TP programs)                                              
   9 *       MN  (all MN programs)                                              
  10 *       VR  (all variable files)                                           
  11 *       SV  (all system files)                                             
  12 *       IO  (I/O config data)                                              
  13 *       DF  (all DEFAULT files)                                            
  14 *       ML  (all part model files)                                         
  15 *       BMP  (all bit-map images)                                          
  16 *       PMC  (all PMC files)                                               
  17 *       VA  (all Variable Listings)                                        
  18 *       DG  (all Diagnostic files)                                         
  19 *       VD  (all Vision VD files)                                          
  20 *       IBG  (all IBG files)                                               
Press DIR to generate directory                                                 
[ TYPE ] [ DIR ]  LOAD  [BACKUP]|UTIL |>                                        
========================================
F5([UTIL ]>) is pressed                
31-AUG-26 12:43 :16
--Screen image--------------------------
TPIF-149 Must complete operation first                                          
PLACE_VICE1_T2    LINE 0    \T1\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
FILE\\\\\\\\\\\\\\\\\\\\\\\\\\       0 1                                        
UT1:\*.*                          1/32                                          
\\\1\*\\\\\\\*\\\(all\files)\\\\\\\\\\\\                                        
   2 *       KL  (all KAREL source)                                             
   3 *       CF  (all command files)                                            
   4 *       TX  (all text files)                                               
   5 *       LS  (all KAREL listings)                                           
   6 *       DT  (all KAREL data files)                                         
   7 *       PC  (all KAREL p-code)                                             
   8 *       TP  (all TP programs)                                              
   9 *       MN  (all MN programs)                                              
  10 *       VR  (all variable files)                                           
  11 *       SV  (all system files)                                             
  12 *       IO  (I/O config data)                                              
  13 *       DF  (all DEFAULT files)                                            
  14 *       ML  (all part model files)                                         
  15 *       BMP  (all bit-map images)                                          
  16 *       PMC  (all PMC files)                                               
  17 *       VA  (all Variable Listings)                                        
  18 *       DG  (all Diagnostic files)                                         
  19 *       VD  (all Vision VD files)                                          
  20 *       IBG  (all IBG files)                                               
Press DIR to generate directory                                                 
[ TYPE ] [ DIR ]  LOAD  [BACKUP][UTIL ]>                                        
========================================
ENTER is pressed                       
31-AUG-26 12:43 :16
========================================
ENTER is pressed                       
31-AUG-26 12:43 :10
========================================
'USB on TP (UT1:)' is selected         
31-AUG-26 12:43 :02
--Screen image--------------------------
TPIF-149 Must complete operation first                                          
PLACE_VICE1_T2    LINE 0    \T1\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
FILE\\\\\\\\\\\\\\\\\\\\\\\\\\       0 1                                        
UT1:\*.*                          1/32                                          
\\\1\*\\\\\\\*\\\(all\files)\\\\\\\\\\\\                                        
   2 *       KL  (all KAREL source)                                             
   3 *       CF  (all command files)                                            
   4 *       TX  (all text files)                                               
   5 *       LS  (all KAREL listings)                                           
   6 *       DT  (all KAREL data files)                                         
   7 *       PC  (all KAREL p-code)                                             
   8 *       TP  (all TP programs)                                              
   9 *       MN  (all MN programs)                                              
  10 *       VR  (all variable files)                                           
  11 *       SV  (all system files)                                             
  12 *       IO  (I/O config data)                                              
  13 *       DF  (all DEFAULT files)                                            
  14 *       ML  (all part model files)                                         
  15 *       BMP  (all bit-map images)                                          
  16 *       PMC  (all PMC files)                                               
  17 *       VA  (all Variable Listings)                                        
  18 *       DG  (all Diagnostic files)                                         
  19 *       VD  (all Vision VD files)                                          
  20 *       IBG  (all IBG files)                                               
Press DIR to generate directory                                                 
[ TYPE ] [ DIR ]  LOAD  [BACKUP][UTIL ]>                                        
========================================
'Set Device' is selected               
31-AUG-26 12:42 :34
--Screen image--------------------------
TPIF-149 Must complete operation first                                          
PLACE_VICE1_T2    LINE 0    \T1\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
FILE\\\\\\\\\\\\\\\\\\\\\\\\\\       0 1                                        
UT1:\*.*                          1/32                                          
\\\1\*\\\\\\\*\\\(all\files)\\\\\\\\\\\\                                        
   2 *       KL  (all KAREL source)                                             
   3 *       CF  (all command files)                                            
   4 *       TX  (all text files)                                               
   5 *       LS  (all KAREL listings)                                           
   6 *       DT  (all KAREL data files)                                         
   7 *       PC  (all KAREL p-code)                                             
   8 *       TP  (all TP programs)                                              
   9 *       MN  (all MN programs)                                              
  10 *       VR  (all variable files)                                           
  11 *       SV  (all system files)                                             
  12 *       IO  (I/O config data)                                              
  13 *       DF  (all DEFAULT files)                                            
  14 *       ML  (all part model files)                                         
  15 *       BMP  (all bit-map images)                                          
  16 *       PMC  (all PMC files)                                               
  17 *       VA  (all Variable Listings)                                        
  18 *       DG  (all Diagnostic files)                                         
  19 *       VD  (all Vision VD files)                                          
  20 *       IBG  (all IBG files)                                               
Press DIR to generate directory                                                 
[ TYPE ] [ DIR ]  LOAD  [BACKUP]|UTIL |>                                        
========================================
F5([UTIL ]>) is pressed                
31-AUG-26 12:42 :26
--Screen image--------------------------
TPIF-149 Must complete operation first                                          
PLACE_VICE1_T2    LINE 0    \T1\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
FILE\\\\\\\\\\\\\\\\\\\\\\\\\\       0 1                                        
UT1:\*.*                          1/32                                          
\\\1\*\\\\\\\*\\\(all\files)\\\\\\\\\\\\                                        
   2 *       KL  (all KAREL source)                                             
   3 *       CF  (all command files)                                            
   4 *       TX  (all text files)                                               
   5 *       LS  (all KAREL listings)                                           
   6 *       DT  (all KAREL data files)                                         
   7 *       PC  (all KAREL p-code)                                             
   8 *       TP  (all TP programs)                                              
   9 *       MN  (all MN programs)                                              
  10 *       VR  (all variable files)                                           
  11 *       SV  (all system files)                                             
  12 *       IO  (I/O config data)                                              
  13 *       DF  (all DEFAULT files)                                            
  14 *       ML  (all part model files)                                         
  15 *       BMP  (all bit-map images)                                          
  16 *       PMC  (all PMC files)                                               
  17 *       VA  (all Variable Listings)                                        
  18 *       DG  (all Diagnostic files)                                         
  19 *       VD  (all Vision VD files)                                          
  20 *       IBG  (all IBG files)                                               
Press DIR to generate directory                                                 
[ TYPE ] [ DIR ]  LOAD  [BACKUP][UTIL ]>                                        
========================================
ENTER is pressed                       
31-AUG-26 12:42 :22
========================================
LLL is entered                         
31-AUG-26 12:41 :50
--Screen image--------------------------
TPIF-149 Must complete operation first                                          
PLACE_VICE1_T2    LINE 0    \T1\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
FILE\\\\\\\\\\\\\\\\\\\\\\\\\\       0 1                                        
UT1:\*.*                          1/32                                          
\\\1\*\\\\\\\*\\\(all\files)\\\\\\\\\\\\                                        
   2 *       KL  (all KAREL source)                                             
   3 *       CF  (all command files)                                            
   4 *       TX  (all text files)                                               
   5 *       LS  (all KAREL listings)                                           
   6 *       DT  (all KAREL data files)                                         
   7 *       PC  (all KAREL p-code)                                             
   8 *       TP  (all TP programs)                                              
   9 *       MN  (all MN programs)                                              
  10 *       VR  (all variable files)                                           
  11 *       SV  (all system files)                                             
  12 *       IO  (I/O config data)                                              
  13 *       DF  (all DEFAULT files)                                            
  14 *       ML  (all part model files)                                         
  15 *       BMP  (all bit-map images)                                          
  16 *       PMC  (all PMC files)                                               
  17 *       VA  (all Variable Listings)                                        
  18 *       DG  (all Diagnostic files)                                         
  19 *       VD  (all Vision VD files)                                          
  20 *       IBG  (all IBG files)                                               
Directory name:                                                                 
   PRG    MAIN     SUB    TEST                                                  
========================================
lll is entered                         
31-AUG-26 12:41 :46
--Screen image--------------------------
TPIF-149 Must complete operation first                                          
PLACE_VICE1_T2    LINE 0    \T1\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
FILE\\\\\\\\\\\\\\\\\\\\\\\\\\       0 1                                        
UT1:\*.*                          1/32                                          
\\\1\*\\\\\\\*\\\(all\files)\\\\\\\\\\\\                                        
   2 *       KL  (all KAREL source)                                             
   3 *       CF  (all command files)                                            
   4 *       TX  (all text files)                                               
   5 *       LS  (all KAREL listings)                                           
   6 *       DT  (all KAREL data files)                                         
   7 *       PC  (all KAREL p-code)                                             
   8 *       TP  (all TP programs)                                              
   9 *       MN  (all MN programs)                                              
  10 *       VR  (all variable files)                                           
  11 *       SV  (all system files)                                             
  12 *       IO  (I/O config data)                                              
  13 *       DF  (all DEFAULT files)                                            
  14 *       ML  (all part model files)                                         
  15 *       BMP  (all bit-map images)                                          
  16 *       PMC  (all PMC files)                                               
  17 *       VA  (all Variable Listings)                                        
  18 *       DG  (all Diagnostic files)                                         
  19 *       VD  (all Vision VD files)                                          
  20 *       IBG  (all IBG files)                                               
Directory name:                                                                 
   PRG    MAIN     SUB    TEST                                                  
========================================
'Make DIR' is selected                 
31-AUG-26 12:41 :34
--Screen image--------------------------
TPIF-149 Must complete operation first                                          
PLACE_VICE1_T2    LINE 0    \T1\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
FILE\\\\\\\\\\\\\\\\\\\\\\\\\\       0 1                                        
UT1:\*.*                          1/32                                          
\\\1\*\\\\\\\*\\\(all\files)\\\\\\\\\\\\                                        
   2 *       KL  (all KAREL source)                                             
   3 *       CF  (all command files)                                            
   4 *       TX  (all text files)                                               
   5 *       LS  (all KAREL listings)                                           
   6 *       DT  (all KAREL data files)                                         
   7 *       PC  (all KAREL p-code)                                             
   8 *       TP  (all TP programs)                                              
   9 *       MN  (all MN programs)                                              
  10 *       VR  (all variable files)                                           
  11 *       SV  (all system files)                                             
  12 *       IO  (I/O config data)                                              
  13 *       DF  (all DEFAULT files)                                            
  14 *       ML  (all part model files)                                         
  15 *       BMP  (all bit-map images)                                          
  16 *       PMC  (all PMC files)                                               
  17 *       VA  (all Variable Listings)                                        
  18 *       DG  (all Diagnostic files)                                         
  19 *       VD  (all Vision VD files)                                          
  20 *       IBG  (all IBG files)                                               
Press DIR to generate directory                                                 
[ TYPE ] [ DIR ]  LOAD  [BACKUP]|UTIL |>                                        
========================================
F5([UTIL ]>) is pressed                
31-AUG-26 12:41 :32
--Screen image--------------------------
TPIF-149 Must complete operation first                                          
PLACE_VICE1_T2    LINE 0    \T1\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
FILE\\\\\\\\\\\\\\\\\\\\\\\\\\       0 1                                        
UT1:\*.*                          1/32                                          
\\\1\*\\\\\\\*\\\(all\files)\\\\\\\\\\\\                                        
   2 *       KL  (all KAREL source)                                             
   3 *       CF  (all command files)                                            
   4 *       TX  (all text files)                                               
   5 *       LS  (all KAREL listings)                                           
   6 *       DT  (all KAREL data files)                                         
   7 *       PC  (all KAREL p-code)                                             
   8 *       TP  (all TP programs)                                              
   9 *       MN  (all MN programs)                                              
  10 *       VR  (all variable files)                                           
  11 *       SV  (all system files)                                             
  12 *       IO  (I/O config data)                                              
  13 *       DF  (all DEFAULT files)                                            
  14 *       ML  (all part model files)                                         
  15 *       BMP  (all bit-map images)                                          
  16 *       PMC  (all PMC files)                                               
  17 *       VA  (all Variable Listings)                                        
  18 *       DG  (all Diagnostic files)                                         
  19 *       VD  (all Vision VD files)                                          
  20 *       IBG  (all IBG files)                                               
Press DIR to generate directory                                                 
[ TYPE ] [ DIR ]  LOAD  [BACKUP][UTIL ]>                                        
========================================
F5(   NO   ) is pressed                
31-AUG-26 12:41 :30
--Screen image--------------------------
TPIF-149 Must complete operation first                                          
PLACE_VICE1_T2    LINE 0    \T1\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
FILE\Format\\\\\\\\\\\\\\\\\\\       0 1                                        
UT1:\*.*                          1/32                                          
                                                                                
           Formatting UT1:                                                      
                                                                                
*************  WARNING  ****************                                        
  ANY DATA ON THE DISK WILL BE LOST!                                            
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
Format disk?                                                                    
                          YES      NO                                           
========================================
'Format' is selected                   
31-AUG-26 12:41 :26
--Screen image--------------------------
TPIF-149 Must complete operation first                                          
PLACE_VICE1_T2    LINE 0    \T1\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
FILE\\\\\\\\\\\\\\\\\\\\\\\\\\       0 1                                        
UT1:\*.*                          1/32                                          
\\\1\*\\\\\\\*\\\(all\files)\\\\\\\\\\\\                                        
   2 *       KL  (all KAREL source)                                             
   3 *       CF  (all command files)                                            
   4 *       TX  (all text files)                                               
   5 *       LS  (all KAREL listings)                                           
   6 *       DT  (all KAREL data files)                                         
   7 *       PC  (all KAREL p-code)                                             
   8 *       TP  (all TP programs)                                              
   9 *       MN  (all MN programs)                                              
  10 *       VR  (all variable files)                                           
  11 *       SV  (all system files)                                             
  12 *       IO  (I/O config data)                                              
  13 *       DF  (all DEFAULT files)                                            
  14 *       ML  (all part model files)                                         
  15 *       BMP  (all bit-map images)                                          
  16 *       PMC  (all PMC files)                                               
  17 *       VA  (all Variable Listings)                                        
  18 *       DG  (all Diagnostic files)                                         
  19 *       VD  (all Vision VD files)                                          
  20 *       IBG  (all IBG files)                                               
Press DIR to generate directory                                                 
[ TYPE ] [ DIR ]  LOAD  [BACKUP]|UTIL |>                                        
========================================
F5([UTIL ]>) is pressed                
31-AUG-26 12:41 :26
--Screen image--------------------------
TPIF-149 Must complete operation first                                          
PLACE_VICE1_T2    LINE 0    \T1\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
FILE\\\\\\\\\\\\\\\\\\\\\\\\\\       0 1                                        
UT1:\*.*                          1/32                                          
\\\1\*\\\\\\\*\\\(all\files)\\\\\\\\\\\\                                        
   2 *       KL  (all KAREL source)                                             
   3 *       CF  (all command files)                                            
   4 *       TX  (all text files)                                               
   5 *       LS  (all KAREL listings)                                           
   6 *       DT  (all KAREL data files)                                         
   7 *       PC  (all KAREL p-code)                                             
   8 *       TP  (all TP programs)                                              
   9 *       MN  (all MN programs)                                              
  10 *       VR  (all variable files)                                           
  11 *       SV  (all system files)                                             
  12 *       IO  (I/O config data)                                              
  13 *       DF  (all DEFAULT files)                                            
  14 *       ML  (all part model files)                                         
  15 *       BMP  (all bit-map images)                                          
  16 *       PMC  (all PMC files)                                               
  17 *       VA  (all Variable Listings)                                        
  18 *       DG  (all Diagnostic files)                                         
  19 *       VD  (all Vision VD files)                                          
  20 *       IBG  (all IBG files)                                               
Press DIR to generate directory                                                 
[ TYPE ] [ DIR ]  LOAD  [BACKUP][UTIL ]>                                        
========================================
 is entered                            
31-AUG-26 12:41 :24
--Screen image--------------------------
TPIF-149 Must complete operation first                                          
PLACE_VICE1_T2    LINE 0    \T1\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
FILE\\\\\\\\\\\\\\\\\\\\\\\\\\       0 1                                        
UT1:\*.*                          1/32                                          
\\\1\*\\\\\\\*\\\(all\files)\\\\\\\\\\\\                                        
   2 *       KL  (all KAREL source)                                             
   3 *       CF  (all command files)                                            
   4 *       TX  (all text files)                                               
   5 *       LS  (all KAREL listings)                                           
   6 *       DT  (all KAREL data files)                                         
   7 *       PC  (all KAREL p-code)                                             
   8 *       TP  (all TP programs)                                              
   9 *       MN  (all MN programs)                                              
  10 *       VR  (all variable files)                                           
  11 *       SV  (all system files)                                             
  12 *       IO  (I/O config data)                                              
  13 *       DF  (all DEFAULT files)                                            
  14 *       ML  (all part model files)                                         
  15 *       BMP  (all bit-map images)                                          
  16 *       PMC  (all PMC files)                                               
  17 *       VA  (all Variable Listings)                                        
  18 *       DG  (all Diagnostic files)                                         
  19 *       VD  (all Vision VD files)                                          
  20 *       IBG  (all IBG files)                                               
Directory name:                                                                 
   PRG    MAIN     SUB    TEST                                                  
========================================
'Make DIR' is selected                 
31-AUG-26 12:41 :22
--Screen image--------------------------
TPIF-149 Must complete operation first                                          
PLACE_VICE1_T2    LINE 0    \T1\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
FILE\\\\\\\\\\\\\\\\\\\\\\\\\\       0 1                                        
UT1:\*.*                          1/32                                          
\\\1\*\\\\\\\*\\\(all\files)\\\\\\\\\\\\                                        
   2 *       KL  (all KAREL source)                                             
   3 *       CF  (all command files)                                            
   4 *       TX  (all text files)                                               
   5 *       LS  (all KAREL listings)                                           
   6 *       DT  (all KAREL data files)                                         
   7 *       PC  (all KAREL p-code)                                             
   8 *       TP  (all TP programs)                                              
   9 *       MN  (all MN programs)                                              
  10 *       VR  (all variable files)                                           
  11 *       SV  (all system files)                                             
  12 *       IO  (I/O config data)                                              
  13 *       DF  (all DEFAULT files)                                            
  14 *       ML  (all part model files)                                         
  15 *       BMP  (all bit-map images)                                          
  16 *       PMC  (all PMC files)                                               
  17 *       VA  (all Variable Listings)                                        
  18 *       DG  (all Diagnostic files)                                         
  19 *       VD  (all Vision VD files)                                          
  20 *       IBG  (all IBG files)                                               
                                                                                
[ TYPE ] [ DIR ]  LOAD  [BACKUP]|UTIL |>                                        
========================================
F5([UTIL ]>) is pressed                
31-AUG-26 12:41 :20
--Screen image--------------------------
TPIF-149 Must complete operation first                                          
PLACE_VICE1_T2    LINE 0    \T1\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
FILE\\\\\\\\\\\\\\\\\\\\\\\\\\       0 1                                        
UT1:\*.*                          1/32                                          
\\\1\*\\\\\\\*\\\(all\files)\\\\\\\\\\\\                                        
   2 *       KL  (all KAREL source)                                             
   3 *       CF  (all command files)                                            
   4 *       TX  (all text files)                                               
   5 *       LS  (all KAREL listings)                                           
   6 *       DT  (all KAREL data files)                                         
   7 *       PC  (all KAREL p-code)                                             
   8 *       TP  (all TP programs)                                              
   9 *       MN  (all MN programs)                                              
  10 *       VR  (all variable files)                                           
  11 *       SV  (all system files)                                             
  12 *       IO  (I/O config data)                                              
  13 *       DF  (all DEFAULT files)                                            
  14 *       ML  (all part model files)                                         
  15 *       BMP  (all bit-map images)                                          
  16 *       PMC  (all PMC files)                                               
  17 *       VA  (all Variable Listings)                                        
  18 *       DG  (all Diagnostic files)                                         
  19 *       VD  (all Vision VD files)                                          
  20 *       IBG  (all IBG files)                                               
                                                                                
[ TYPE ] [ DIR ]  LOAD  [BACKUP][UTIL ]>                                        
========================================
 is entered                            
31-AUG-26 12:41 :12
--Screen image--------------------------
SYST-043 TP disabled in T1/T2 mode                                              
PLACE_VICE1_T2    LINE 0    \T1\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
FILE\\\\\\\\\\\\\\\\\\\\\\\\\\       0 1                                        
UT1:\*.*                          1/32                                          
\\\1\*\\\\\\\*\\\(all\files)\\\\\\\\\\\\                                        
   2 *       KL  (all KAREL source)                                             
   3 *       CF  (all command files)                                            
   4 *       TX  (all text files)                                               
   5 *       LS  (all KAREL listings)                                           
   6 *       DT  (all KAREL data files)                                         
   7 *       PC  (all KAREL p-code)                                             
   8 *       TP  (all TP programs)                                              
   9 *       MN  (all MN programs)                                              
  10 *       VR  (all variable files)                                           
  11 *       SV  (all system files)                                             
  12 *       IO  (I/O config data)                                              
  13 *       DF  (all DEFAULT files)                                            
  14 *       ML  (all part model files)                                         
  15 *       BMP  (all bit-map images)                                          
  16 *       PMC  (all PMC files)                                               
  17 *       VA  (all Variable Listings)                                        
  18 *       DG  (all Diagnostic files)                                         
  19 *       VD  (all Vision VD files)                                          
  20 *       IBG  (all IBG files)                                               
Directory name:                                                                 
   PRG    MAIN     SUB    TEST                                                  
========================================
 is entered                            
31-AUG-26 12:41 :08
--Screen image--------------------------
SYST-043 TP disabled in T1/T2 mode                                              
PLACE_VICE1_T2    LINE 0    \T1\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
FILE\\\\\\\\\\\\\\\\\\\\\\\\\\       0 1                                        
UT1:\*.*                          1/32                                          
\\\1\*\\\\\\\*\\\(all\files)\\\\\\\\\\\\                                        
   2 *       KL  (all KAREL source)                                             
   3 *       CF  (all command files)                                            
   4 *       TX  (all text files)                                               
   5 *       LS  (all KAREL listings)                                           
   6 *       DT  (all KAREL data files)                                         
   7 *       PC  (all KAREL p-code)                                             
   8 *       TP  (all TP programs)                                              
   9 *       MN  (all MN programs)                                              
  10 *       VR  (all variable files)                                           
  11 *       SV  (all system files)                                             
  12 *       IO  (I/O config data)                                              
  13 *       DF  (all DEFAULT files)                                            
  14 *       ML  (all part model files)                                         
  15 *       BMP  (all bit-map images)                                          
  16 *       PMC  (all PMC files)                                               
  17 *       VA  (all Variable Listings)                                        
  18 *       DG  (all Diagnostic files)                                         
  19 *       VD  (all Vision VD files)                                          
  20 *       IBG  (all IBG files)                                               
Directory name:                                                                 
   PRG    MAIN     SUB    TEST                                                  
========================================
'Make DIR' is selected                 
31-AUG-26 12:41 :06
--Screen image--------------------------
SYST-043 TP disabled in T1/T2 mode                                              
PLACE_VICE1_T2    LINE 0    \T1\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
FILE\\\\\\\\\\\\\\\\\\\\\\\\\\       0 1                                        
UT1:\*.*                          1/32                                          
\\\1\*\\\\\\\*\\\(all\files)\\\\\\\\\\\\                                        
   2 *       KL  (all KAREL source)                                             
   3 *       CF  (all command files)                                            
   4 *       TX  (all text files)                                               
   5 *       LS  (all KAREL listings)                                           
   6 *       DT  (all KAREL data files)                                         
   7 *       PC  (all KAREL p-code)                                             
   8 *       TP  (all TP programs)                                              
   9 *       MN  (all MN programs)                                              
  10 *       VR  (all variable files)                                           
  11 *       SV  (all system files)                                             
  12 *       IO  (I/O config data)                                              
  13 *       DF  (all DEFAULT files)                                            
  14 *       ML  (all part model files)                                         
  15 *       BMP  (all bit-map images)                                          
  16 *       PMC  (all PMC files)                                               
  17 *       VA  (all Variable Listings)                                        
  18 *       DG  (all Diagnostic files)                                         
  19 *       VD  (all Vision VD files)                                          
  20 *       IBG  (all IBG files)                                               
Press DIR to generate directory                                                 
[ TYPE ] [ DIR ]  LOAD  [BACKUP]|UTIL |>                                        
========================================
F5([UTIL ]>) is pressed                
31-AUG-26 12:41 :06
--Screen image--------------------------
SYST-043 TP disabled in T1/T2 mode                                              
PLACE_VICE1_T2    LINE 0    \T1\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
FILE\\\\\\\\\\\\\\\\\\\\\\\\\\       0 1                                        
UT1:\*.*                          1/32                                          
\\\1\*\\\\\\\*\\\(all\files)\\\\\\\\\\\\                                        
   2 *       KL  (all KAREL source)                                             
   3 *       CF  (all command files)                                            
   4 *       TX  (all text files)                                               
   5 *       LS  (all KAREL listings)                                           
   6 *       DT  (all KAREL data files)                                         
   7 *       PC  (all KAREL p-code)                                             
   8 *       TP  (all TP programs)                                              
   9 *       MN  (all MN programs)                                              
  10 *       VR  (all variable files)                                           
  11 *       SV  (all system files)                                             
  12 *       IO  (I/O config data)                                              
  13 *       DF  (all DEFAULT files)                                            
  14 *       ML  (all part model files)                                         
  15 *       BMP  (all bit-map images)                                          
  16 *       PMC  (all PMC files)                                               
  17 *       VA  (all Variable Listings)                                        
  18 *       DG  (all Diagnostic files)                                         
  19 *       VD  (all Vision VD files)                                          
  20 *       IBG  (all IBG files)                                               
Press DIR to generate directory                                                 
[ TYPE ] [ DIR ]  LOAD  [BACKUP][UTIL ]>                                        
========================================
Menu changed 'FILE'                    
31-AUG-26 12:40 :58
========================================
'File' is selected in 'FILE' MENU flyou
t                                      
31-AUG-26 12:40 :58
========================================
ENTER is pressed                       
31-AUG-26 12:40 :58
========================================
Menu changed ''                        
31-AUG-26 12:40 :52
========================================
SYST-043 TP disabled in T1/T2 mode     
                                       
                                       
STOP.L                        00000110 
31-AUG-26 12:40 :50
========================================
SRVO-233 TP OFF in T1,T2               
                                       
                                       
SERVO                         00110110 
31-AUG-26 12:40 :50
========================================
SRVO-003 Deadman switch released       
                                       
                                       
SERVO                         00110110 
31-AUG-26 12:40 :46
========================================
ROB is entered                         
31-AUG-26 12:40 :40
--Screen image--------------------------
                                                                                
PLACE_VICE1_T2    LINE 0    \T1\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
FILE\\\\\\\\\\\\\\\\\\\\\\\\\\       0 1                                        
UT1:\*.*                          1/32                                          
\\\1\*\\\\\\\*\\\(all\files)\\\\\\\\\\\\                                        
   2 *       KL  (all KAREL source)                                             
   3 *       CF  (all command files)                                            
   4 *       TX  (all text files)                                               
   5 *       LS  (all KAREL listings)                                           
   6 *       DT  (all KAREL data files)                                         
   7 *       PC  (all KAREL p-code)                                             
   8 *       TP  (all TP programs)                                              
   9 *       MN  (all MN programs)                                              
  10 *       VR  (all variable files)                                           
  11 *       SV  (all system files)                                             
  12 *       IO  (I/O config data)                                              
  13 *       DF  (all DEFAULT files)                                            
  14 *       ML  (all part model files)                                         
  15 *       BMP  (all bit-map images)                                          
  16 *       PMC  (all PMC files)                                               
  17 *       VA  (all Variable Listings)                                        
  18 *       DG  (all Diagnostic files)                                         
  19 *       VD  (all Vision VD files)                                          
  20 *       IBG  (all IBG files)                                               
Directory name:                                                                 
   PRG    MAIN     SUB    TEST                                                  
========================================
ROB is entered                         
31-AUG-26 12:40 :38
--Screen image--------------------------
                                                                                
PLACE_VICE1_T2    LINE 0    \T1\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
FILE\\\\\\\\\\\\\\\\\\\\\\\\\\       0 1                                        
UT1:\*.*                          1/32                                          
\\\1\*\\\\\\\*\\\(all\files)\\\\\\\\\\\\                                        
   2 *       KL  (all KAREL source)                                             
   3 *       CF  (all command files)                                            
   4 *       TX  (all text files)                                               
   5 *       LS  (all KAREL listings)                                           
   6 *       DT  (all KAREL data files)                                         
   7 *       PC  (all KAREL p-code)                                             
   8 *       TP  (all TP programs)                                              
   9 *       MN  (all MN programs)                                              
  10 *       VR  (all variable files)                                           
  11 *       SV  (all system files)                                             
  12 *       IO  (I/O config data)                                              
  13 *       DF  (all DEFAULT files)                                            
  14 *       ML  (all part model files)                                         
  15 *       BMP  (all bit-map images)                                          
  16 *       PMC  (all PMC files)                                               
  17 *       VA  (all Variable Listings)                                        
  18 *       DG  (all Diagnostic files)                                         
  19 *       VD  (all Vision VD files)                                          
  20 *       IBG  (all IBG files)                                               
Directory name:                                                                 
   PRG    MAIN     SUB    TEST                                                  
========================================
rob is entered                         
31-AUG-26 12:40 :32
--Screen image--------------------------
                                                                                
PLACE_VICE1_T2    LINE 0    \T1\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
FILE\\\\\\\\\\\\\\\\\\\\\\\\\\       0 1                                        
UT1:\*.*                          1/32                                          
\\\1\*\\\\\\\*\\\(all\files)\\\\\\\\\\\\                                        
   2 *       KL  (all KAREL source)                                             
   3 *       CF  (all command files)                                            
   4 *       TX  (all text files)                                               
   5 *       LS  (all KAREL listings)                                           
   6 *       DT  (all KAREL data files)                                         
   7 *       PC  (all KAREL p-code)                                             
   8 *       TP  (all TP programs)                                              
   9 *       MN  (all MN programs)                                              
  10 *       VR  (all variable files)                                           
  11 *       SV  (all system files)                                             
  12 *       IO  (I/O config data)                                              
  13 *       DF  (all DEFAULT files)                                            
  14 *       ML  (all part model files)                                         
  15 *       BMP  (all bit-map images)                                          
  16 *       PMC  (all PMC files)                                               
  17 *       VA  (all Variable Listings)                                        
  18 *       DG  (all Diagnostic files)                                         
  19 *       VD  (all Vision VD files)                                          
  20 *       IBG  (all IBG files)                                               
Directory name:                                                                 
   PRG    MAIN     SUB    TEST                                                  
========================================
'Make DIR' is selected                 
31-AUG-26 12:40 :24
--Screen image--------------------------
                                                                                
PLACE_VICE1_T2    LINE 0    \T1\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
FILE\\\\\\\\\\\\\\\\\\\\\\\\\\       0 1                                        
UT1:\*.*                          1/32                                          
\\\1\*\\\\\\\*\\\(all\files)\\\\\\\\\\\\                                        
   2 *       KL  (all KAREL source)                                             
   3 *       CF  (all command files)                                            
   4 *       TX  (all text files)                                               
   5 *       LS  (all KAREL listings)                                           
   6 *       DT  (all KAREL data files)                                         
   7 *       PC  (all KAREL p-code)                                             
   8 *       TP  (all TP programs)                                              
   9 *       MN  (all MN programs)                                              
  10 *       VR  (all variable files)                                           
  11 *       SV  (all system files)                                             
  12 *       IO  (I/O config data)                                              
  13 *       DF  (all DEFAULT files)                                            
  14 *       ML  (all part model files)                                         
  15 *       BMP  (all bit-map images)                                          
  16 *       PMC  (all PMC files)                                               
  17 *       VA  (all Variable Listings)                                        
  18 *       DG  (all Diagnostic files)                                         
  19 *       VD  (all Vision VD files)                                          
  20 *       IBG  (all IBG files)                                               
                                                                                
[ TYPE ] [ DIR ]  LOAD  [BACKUP]|UTIL |>                                        
========================================
F5([UTIL ]>) is pressed                
31-AUG-26 12:40 :24
--Screen image--------------------------
                                                                                
PLACE_VICE1_T2    LINE 0    \T1\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
FILE\\\\\\\\\\\\\\\\\\\\\\\\\\       0 1                                        
UT1:\*.*                          1/32                                          
\\\1\*\\\\\\\*\\\(all\files)\\\\\\\\\\\\                                        
   2 *       KL  (all KAREL source)                                             
   3 *       CF  (all command files)                                            
   4 *       TX  (all text files)                                               
   5 *       LS  (all KAREL listings)                                           
   6 *       DT  (all KAREL data files)                                         
   7 *       PC  (all KAREL p-code)                                             
   8 *       TP  (all TP programs)                                              
   9 *       MN  (all MN programs)                                              
  10 *       VR  (all variable files)                                           
  11 *       SV  (all system files)                                             
  12 *       IO  (I/O config data)                                              
  13 *       DF  (all DEFAULT files)                                            
  14 *       ML  (all part model files)                                         
  15 *       BMP  (all bit-map images)                                          
  16 *       PMC  (all PMC files)                                               
  17 *       VA  (all Variable Listings)                                        
  18 *       DG  (all Diagnostic files)                                         
  19 *       VD  (all Vision VD files)                                          
  20 *       IBG  (all IBG files)                                               
                                                                                
[ TYPE ] [ DIR ]  LOAD  [BACKUP][UTIL ]>                                        
========================================
F5(   NO   ) is pressed                
31-AUG-26 12:40 :20
--Screen image--------------------------
                                                                                
PLACE_VICE1_T2    LINE 0    \T1\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
FILE\\\\\\\\\\\\\\\\\\\\\\\\\\       0 1                                        
UT1:\*.*                          1/32                                          
\\\1\*\\\\\\\*\\\(all\files)\\\\\\\\\\\\                                        
   2 *       KL  (all KAREL source)                                             
   3 *       CF  (all command files)                                            
   4 *       TX  (all text files)                                               
   5 *       LS  (all KAREL listings)                                           
   6 *       DT  (all KAREL data files)                                         
   7 *       PC  (all KAREL p-code)                                             
   8 *       TP  (all TP programs)                                              
   9 *       MN  (all MN programs)                                              
  10 *       VR  (all variable files)                                           
  11 *       SV  (all system files)                                             
  12 *       IO  (I/O config data)                                              
  13 *       DF  (all DEFAULT files)                                            
  14 *       ML  (all part model files)                                         
  15 *       BMP  (all bit-map images)                                          
  16 *       PMC  (all PMC files)                                               
  17 *       VA  (all Variable Listings)                                        
  18 *       DG  (all Diagnostic files)                                         
  19 *       VD  (all Vision VD files)                                          
  20 *       IBG  (all IBG files)                                               
Load UT1:\*.*?                                                                  
                          YES      NO                                           
========================================
F3(  LOAD  ) is pressed                
31-AUG-26 12:40 :18
--Screen image--------------------------
                                                                                
PLACE_VICE1_T2    LINE 0    \T1\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
FILE\\\\\\\\\\\\\\\\\\\\\\\\\\       0 1                                        
UT1:\*.*                          1/32                                          
\\\1\*\\\\\\\*\\\(all\files)\\\\\\\\\\\\                                        
   2 *       KL  (all KAREL source)                                             
   3 *       CF  (all command files)                                            
   4 *       TX  (all text files)                                               
   5 *       LS  (all KAREL listings)                                           
   6 *       DT  (all KAREL data files)                                         
   7 *       PC  (all KAREL p-code)                                             
   8 *       TP  (all TP programs)                                              
   9 *       MN  (all MN programs)                                              
  10 *       VR  (all variable files)                                           
  11 *       SV  (all system files)                                             
  12 *       IO  (I/O config data)                                              
  13 *       DF  (all DEFAULT files)                                            
  14 *       ML  (all part model files)                                         
  15 *       BMP  (all bit-map images)                                          
  16 *       PMC  (all PMC files)                                               
  17 *       VA  (all Variable Listings)                                        
  18 *       DG  (all Diagnostic files)                                         
  19 *       VD  (all Vision VD files)                                          
  20 *       IBG  (all IBG files)                                               
                                                                                
[ TYPE ] [ DIR ]  LOAD  [BACKUP][UTIL ]>                                        
========================================
ENTER is pressed                       
31-AUG-26 12:40 :16
========================================
ENTER is pressed                       
31-AUG-26 12:40 :16
========================================
ENTER is pressed                       
31-AUG-26 12:40 :16
========================================
ENTER is pressed                       
31-AUG-26 12:40 :14
========================================
ENTER is pressed                       
31-AUG-26 12:40 :14
========================================
Menu changed 'FILE'                    
31-AUG-26 12:40 :12
========================================
'File' is selected in 'FILE' MENU flyou
t                                      
31-AUG-26 12:40 :12
========================================
ENTER is pressed                       
31-AUG-26 12:40 :12
========================================
Menu changed ''                        
31-AUG-26 12:40 :08
========================================
FILE 'T_NOVICE.LS' is saved            
31-AUG-26 12:40 :08
========================================
FILE 'T_TUTORIAL.LS' is saved          
31-AUG-26 12:40 :08
========================================
FILE 'T_VACOFF.LS' is saved            
31-AUG-26 12:40 :08
========================================
FILE 'T_VACON.LS' is saved             
31-AUG-26 12:40 :08
========================================
FILE 'T_FINCLOS.LS' is saved           
31-AUG-26 12:40 :08
========================================
FILE 'T_FINOPEN.LS' is saved           
31-AUG-26 12:40 :08
========================================
FILE 'T_RAWCLOS.LS' is saved           
31-AUG-26 12:40 :08
========================================
FILE 'T_RAWOPEN.LS' is saved           
31-AUG-26 12:40 :08
========================================
FILE 'T_GRIPCLOS.LS' is saved          
31-AUG-26 12:40 :08
========================================
FILE 'T_GRIPOPEN.LS' is saved          
31-AUG-26 12:40 :08
========================================
FILE 'T_PICKPLACE.LS' is saved         
31-AUG-26 12:40 :08
========================================
FILE 'T_MOVE_ROBOT.LS' is saved        
31-AUG-26 12:40 :08
========================================
FILE 'TEMPLATES.LS' is saved           
31-AUG-26 12:40 :08
========================================
Menu changed 'Auto Backup'             
31-AUG-26 12:40 :02
========================================
'Auto Backup' is selected              
31-AUG-26 12:40 :02
--Screen image--------------------------
                                                                                
PLACE_VICE1_T2    LINE 0    \T1\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
FILE\\\\\\\\\\\\\\\\\\\\\\\\\\       0 1                                        
UT1:\*.*                          1/32                                          
\\\1\*\\\\\\\*\\\(all\files)\\\\\\\\\\\\                                        
   2 *       KL  (all KAREL source)                                             
   3 *       CF  (all command files)                                            
   4 *       TX  (all text files)                                               
   5 *       LS  (all KAREL listings)                                           
   6 *       DT  (all KAREL data files)                                         
   7 *       PC  (all KAREL p-code)                                             
   8 *       TP  (all TP programs)                                              
   9 *       MN  (all MN programs)                                              
  10 *       VR  (all variable files)                                           
  11 *       SV  (all system files)                                             
  12 *       IO  (I/O config data)                                              
  13 *       DF  (all DEFAULT files)                                            
  14 *       ML  (all part model files)                                         
  15 *       BMP  (all bit-map images)                                          
  16 *       PMC  (all PMC files)                                               
  17 *       VA  (all Variable Listings)                                        
  18 *       DG  (all Diagnostic files)                                         
  19 *       VD  (all Vision VD files)                                          
  20 *       IBG  (all IBG files)                                               
Press DIR to generate directory                                                 
| TYPE | [ DIR ]  LOAD  [BACKUP][UTIL ]>                                        
========================================
F1([ TYPE ]) is pressed                
31-AUG-26 12:40 :00
--Screen image--------------------------
                                                                                
PLACE_VICE1_T2    LINE 0    \T1\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
FILE\\\\\\\\\\\\\\\\\\\\\\\\\\       0 1                                        
UT1:\*.*                          1/32                                          
\\\1\*\\\\\\\*\\\(all\files)\\\\\\\\\\\\                                        
   2 *       KL  (all KAREL source)                                             
   3 *       CF  (all command files)                                            
   4 *       TX  (all text files)                                               
   5 *       LS  (all KAREL listings)                                           
   6 *       DT  (all KAREL data files)                                         
   7 *       PC  (all KAREL p-code)                                             
   8 *       TP  (all TP programs)                                              
   9 *       MN  (all MN programs)                                              
  10 *       VR  (all variable files)                                           
  11 *       SV  (all system files)                                             
  12 *       IO  (I/O config data)                                              
  13 *       DF  (all DEFAULT files)                                            
  14 *       ML  (all part model files)                                         
  15 *       BMP  (all bit-map images)                                          
  16 *       PMC  (all PMC files)                                               
  17 *       VA  (all Variable Listings)                                        
  18 *       DG  (all Diagnostic files)                                         
  19 *       VD  (all Vision VD files)                                          
  20 *       IBG  (all IBG files)                                               
Press DIR to generate directory                                                 
[ TYPE ] [ DIR ]  LOAD  [BACKUP][UTIL ]>                                        
========================================
F2( [ DIR ]) is pressed                
31-AUG-26 12:39 :50
--Screen image--------------------------
                                                                                
PLACE_VICE1_T2    LINE 0    \T1\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
FILE\\\\\\\\\\\\\\\\\\\\\\\\\\       0 1                                        
UT1:\*.*                          1/32                                          
\\\1\*\\\\\\\*\\\(all\files)\\\\\\\\\\\\                                        
   2 *       KL  (all KAREL source)                                             
   3 *       CF  (all command files)                                            
   4 *       TX  (all text files)                                               
   5 *       LS  (all KAREL listings)                                           
   6 *       DT  (all KAREL data files)                                         
   7 *       PC  (all KAREL p-code)                                             
   8 *       TP  (all TP programs)                                              
   9 *       MN  (all MN programs)                                              
  10 *       VR  (all variable files)                                           
  11 *       SV  (all system files)                                             
  12 *       IO  (I/O config data)                                              
  13 *       DF  (all DEFAULT files)                                            
  14 *       ML  (all part model files)                                         
  15 *       BMP  (all bit-map images)                                          
  16 *       PMC  (all PMC files)                                               
  17 *       VA  (all Variable Listings)                                        
  18 *       DG  (all Diagnostic files)                                         
  19 *       VD  (all Vision VD files)                                          
  20 *       IBG  (all IBG files)                                               
Press DIR to generate directory                                                 
[ TYPE ] [ DIR ]  LOAD  [BACKUP][UTIL ]>                                        
========================================
BU_030220 is entered                   
31-AUG-26 12:39 :44
--Screen image--------------------------
                                                                                
PLACE_VICE1_T2    LINE 0    \T1\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
FILE\\\\\\\\\\\\\\\\\\\\\\\\\\       0 1                                        
UT1:\*.*                          1/32                                          
\\\1\*\\\\\\\*\\\(all\files)\\\\\\\\\\\\                                        
   2 *       KL  (all KAREL source)                                             
   3 *       CF  (all command files)                                            
   4 *       TX  (all text files)                                               
   5 *       LS  (all KAREL listings)                                           
   6 *       DT  (all KAREL data files)                                         
   7 *       PC  (all KAREL p-code)                                             
   8 *       TP  (all TP programs)                                              
   9 *       MN  (all MN programs)                                              
  10 *       VR  (all variable files)                                           
  11 *       SV  (all system files)                                             
  12 *       IO  (I/O config data)                                              
  13 *       DF  (all DEFAULT files)                                            
  14 *       ML  (all part model files)                                         
  15 *       BMP  (all bit-map images)                                          
  16 *       PMC  (all PMC files)                                               
  17 *       VA  (all Variable Listings)                                        
  18 *       DG  (all Diagnostic files)                                         
  19 *       VD  (all Vision VD files)                                          
  20 *       IBG  (all IBG files)                                               
Directory name:                                                                 
   PRG    MAIN     SUB    TEST                                                  
========================================
BU_030220 is entered                   
31-AUG-26 12:39 :34
--Screen image--------------------------
                                                                                
PLACE_VICE1_T2    LINE 0    \T1\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
FILE\\\\\\\\\\\\\\\\\\\\\\\\\\       0 1                                        
UT1:\*.*                          1/32                                          
\\\1\*\\\\\\\*\\\(all\files)\\\\\\\\\\\\                                        
   2 *       KL  (all KAREL source)                                             
   3 *       CF  (all command files)                                            
   4 *       TX  (all text files)                                               
   5 *       LS  (all KAREL listings)                                           
   6 *       DT  (all KAREL data files)                                         
   7 *       PC  (all KAREL p-code)                                             
   8 *       TP  (all TP programs)                                              
   9 *       MN  (all MN programs)                                              
  10 *       VR  (all variable files)                                           
  11 *       SV  (all system files)                                             
  12 *       IO  (I/O config data)                                              
  13 *       DF  (all DEFAULT files)                                            
  14 *       ML  (all part model files)                                         
  15 *       BMP  (all bit-map images)                                          
  16 *       PMC  (all PMC files)                                               
  17 *       VA  (all Variable Listings)                                        
  18 *       DG  (all Diagnostic files)                                         
  19 *       VD  (all Vision VD files)                                          
  20 *       IBG  (all IBG files)                                               
Directory name:                                                                 
   PRG    MAIN     SUB    TEST                                                  
========================================
BU_030220 is entered                   
31-AUG-26 12:39 :24
--Screen image--------------------------
                                                                                
PLACE_VICE1_T2    LINE 0    \T1\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
FILE\\\\\\\\\\\\\\\\\\\\\\\\\\       0 1                                        
UT1:\*.*                          1/32                                          
\\\1\*\\\\\\\*\\\(all\files)\\\\\\\\\\\\                                        
   2 *       KL  (all KAREL source)                                             
   3 *       CF  (all command files)                                            
   4 *       TX  (all text files)                                               
   5 *       LS  (all KAREL listings)                                           
   6 *       DT  (all KAREL data files)                                         
   7 *       PC  (all KAREL p-code)                                             
   8 *       TP  (all TP programs)                                              
   9 *       MN  (all MN programs)                                              
  10 *       VR  (all variable files)                                           
  11 *       SV  (all system files)                                             
  12 *       IO  (I/O config data)                                              
  13 *       DF  (all DEFAULT files)                                            
  14 *       ML  (all part model files)                                         
  15 *       BMP  (all bit-map images)                                          
  16 *       PMC  (all PMC files)                                               
  17 *       VA  (all Variable Listings)                                        
  18 *       DG  (all Diagnostic files)                                         
  19 *       VD  (all Vision VD files)                                          
  20 *       IBG  (all IBG files)                                               
Directory name:                                                                 
   PRG    MAIN     SUB    TEST                                                  
========================================
BU_030220 is entered                   
31-AUG-26 12:38 :50
--Screen image--------------------------
                                                                                
PLACE_VICE1_T2    LINE 0    \T1\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
FILE\\\\\\\\\\\\\\\\\\\\\\\\\\       0 1                                        
UT1:\*.*                          1/32                                          
\\\1\*\\\\\\\*\\\(all\files)\\\\\\\\\\\\                                        
   2 *       KL  (all KAREL source)                                             
   3 *       CF  (all command files)                                            
   4 *       TX  (all text files)                                               
   5 *       LS  (all KAREL listings)                                           
   6 *       DT  (all KAREL data files)                                         
   7 *       PC  (all KAREL p-code)                                             
   8 *       TP  (all TP programs)                                              
   9 *       MN  (all MN programs)                                              
  10 *       VR  (all variable files)                                           
  11 *       SV  (all system files)                                             
  12 *       IO  (I/O config data)                                              
  13 *       DF  (all DEFAULT files)                                            
  14 *       ML  (all part model files)                                         
  15 *       BMP  (all bit-map images)                                          
  16 *       PMC  (all PMC files)                                               
  17 *       VA  (all Variable Listings)                                        
  18 *       DG  (all Diagnostic files)                                         
  19 *       VD  (all Vision VD files)                                          
  20 *       IBG  (all IBG files)                                               
Directory name:                                                                 
   PRG    MAIN     SUB    TEST                                                  
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
I/O              
========================================
 SO[    7]    OFF -> ON 
Tick:   254601
TB:     110496202
31-AUG-26 12:40 :50
========================================
 SO[    7]    ON  -> OFF
Tick:   254029
TB:     72362688
31-AUG-26 12:40 :50
========================================
 DO[   16]    OFF -> ON 
Tick:   252206
TB:     -49171325
31-AUG-26 12:40 :46
========================================
 SO[    3]    OFF -> ON 
Tick:   252203
TB:     -49371573
31-AUG-26 12:40 :46
========================================
 DO[   16]    ON  -> OFF
Tick:   87272
TB:     1840075800
31-AUG-26 12:35 :16
========================================
 SO[    3]    ON  -> OFF
Tick:   87269
TB:     1839875987
31-AUG-26 12:35 :16
========================================
 DO[   16]    OFF -> ON 
Tick:   86216
TB:     1769675458
31-AUG-26 12:35 :14
========================================
 SO[    3]    OFF -> ON 
Tick:   86213
TB:     1769475676
31-AUG-26 12:35 :14
========================================
 SO[    3]    ON  -> OFF
Tick:   23667
TB:     1894689808
31-AUG-26 12:33 :08
========================================
 DO[   16]    ON  -> OFF
Tick:   23648
TB:     1893423346
31-AUG-26 12:33 :08
========================================
 DI[    8]    ON  -> OFF
Tick:   17466
TB:     1481288110
31-AUG-26 12:32 :56
========================================
 DI[    7]    OFF -> ON 
 DI[    8]    OFF -> ON 
 DI[   13]    OFF -> ON 
Tick:   17400
TB:     1476888008
31-AUG-26 12:32 :56
========================================
 RO[    1]    OFF -> ON 
 RO[    3]    OFF -> ON 
 RO[    6]    OFF -> ON 
Tick:   14713
TB:     1297754200
31-AUG-26 12:32 :50
========================================
 DO[   14]    OFF -> ON 
 DO[   16]    OFF -> ON 
Tick:   14694
TB:     1296487367
31-AUG-26 12:32 :50
========================================
 SO[    2]    ON  -> OFF
Tick:   14603
TB:     1290420363
31-AUG-26 12:32 :50
========================================
 DI[ 1097]    OFF
 DI[ 1098]    OFF
 DI[ 1099]    OFF
 DI[ 1100]    OFF
 DI[ 1101]    OFF
 DI[ 1102]    OFF
 DI[ 1103]    OFF
 DI[ 1104]    OFF
Tick:   14602
TB:     1290353724
31-AUG-26 12:32 :50
========================================
 DO[  117]    OFF
 DO[  118]    OFF
 DO[  119]    OFF
 DO[  120]    OFF
 DO[  121]    OFF
 DO[  122]    OFF
 DO[  123]    OFF
 DO[  124]    OFF
 DO[ 1041]    OFF
 DO[ 1042]    OFF
 DO[ 1043]    OFF
 DO[ 1044]    OFF
 DO[ 1045]    OFF
 DO[ 1046]    OFF
 DO[ 1047]    OFF
 DO[ 1048]    OFF
 DO[ 1049]    OFF
 DO[ 1050]    OFF
 DO[ 1051]    OFF
 DO[ 1052]    OFF
 DO[ 1053]    OFF
 DO[ 1054]    OFF
 DO[ 1055]    OFF
 DO[ 1056]    OFF
 DO[ 1057]    OFF
 DO[ 1058]    OFF
 DO[ 1059]    OFF
 DO[ 1060]    OFF
 DO[ 1061]    OFF
 DO[ 1062]    OFF
 DO[ 1063]    OFF
 DO[ 1064]    OFF
 DO[ 1065]    OFF
 DO[ 1066]    OFF
 DO[ 1067]    OFF
 DO[ 1068]    OFF
 DO[ 1069]    OFF
 DO[ 1070]    OFF
 DO[ 1071]    OFF
 DO[ 1072]    OFF
 DO[ 1073]    OFF
 DO[ 1074]    OFF
 DO[ 1075]    OFF
 DO[ 1076]    OFF
 DO[ 1077]    OFF
 DO[ 1078]    OFF
 DO[ 1079]    OFF
 DO[ 1080]    OFF
 DO[ 1081]    OFF
 DO[ 1082]    OFF
 DO[ 1083]    OFF
 DO[ 1084]    OFF
 DO[ 1085]    OFF
 DO[ 1086]    OFF
 DO[ 1087]    OFF
 DO[ 1088]    OFF
 DO[ 1089]    OFF
 DO[ 1090]    OFF
 DO[ 1091]    OFF
 DO[ 1092]    OFF
 DO[ 1093]    OFF
 DO[ 1094]    OFF
 DO[ 1095]    OFF
 DO[ 1096]    OFF
 DO[ 1097]    OFF
 DO[ 1098]    OFF
 DO[ 1099]    OFF
 DO[ 1100]    OFF
 DO[ 1101]    OFF
 DO[ 1102]    OFF
 DO[ 1103]    OFF
 DO[ 1104]    OFF
 DI[ 1041]    OFF
 DI[ 1042]    OFF
 DI[ 1043]    OFF
 DI[ 1044]    OFF
 DI[ 1045]    OFF
 DI[ 1046]    OFF
 DI[ 1047]    OFF
 DI[ 1048]    OFF
 DI[ 1049]    OFF
 DI[ 1050]    OFF
 DI[ 1051]    OFF
 DI[ 1052]    OFF
 DI[ 1053]    OFF
 DI[ 1054]    OFF
 DI[ 1055]    OFF
 DI[ 1056]    OFF
 DI[ 1057]    OFF
 DI[ 1058]    OFF
 DI[ 1059]    OFF
 DI[ 1060]    OFF
 DI[ 1061]    OFF
 DI[ 1062]    OFF
 DI[ 1063]    OFF
 DI[ 1064]    OFF
 DI[ 1065]    OFF
 DI[ 1066]    OFF
 DI[ 1067]    OFF
 DI[ 1068]    OFF
 DI[ 1069]    OFF
 DI[ 1070]    OFF
 DI[ 1071]    OFF
 DI[ 1072]    OFF
 DI[ 1073]    OFF
 DI[ 1074]    OFF
 DI[ 1075]    OFF
 DI[ 1076]    OFF
 DI[ 1077]    OFF
 DI[ 1078]    OFF
 DI[ 1079]    OFF
 DI[ 1080]    OFF
 DI[ 1081]    OFF
 DI[ 1082]    OFF
 DI[ 1083]    OFF
 DI[ 1084]    OFF
 DI[ 1085]    OFF
 DI[ 1086]    OFF
 DI[ 1087]    OFF
 DI[ 1088]    OFF
 DI[ 1089]    OFF
 DI[ 1090]    OFF
 DI[ 1091]    OFF
 DI[ 1092]    OFF
 DI[ 1093]    OFF
 DI[ 1094]    OFF
 DI[ 1095]    OFF
 DI[ 1096]    OFF
Tick:   14601
TB:     1290287312
31-AUG-26 12:32 :50
========================================
 DO[ 1973]    OFF
 DO[ 1974]    OFF
 DO[ 1975]    OFF
 DO[ 1976]    OFF
 DO[ 1977]    OFF
 DO[ 1978]    OFF
 DO[ 1979]    OFF
 DO[ 1980]    OFF
 DO[ 1981]    OFF
 DO[ 1982]    OFF
 DO[ 1983]    OFF
 DO[ 1984]    OFF
 DO[ 1985]    OFF
 DO[ 1986]    OFF
 DO[ 1987]    OFF
 DO[ 1988]    OFF
 DO[ 1989]    OFF
 DO[ 1990]    OFF
 DO[ 1991]    OFF
 DO[ 1992]    OFF
 DO[ 1993]    OFF
 DO[ 1994]    OFF
 DO[ 1995]    OFF
 DO[ 1996]    OFF
 DO[ 1997]    OFF
 DO[ 1998]    OFF
 DO[ 1999]    OFF
 DO[ 2000]    OFF
 DO[ 2001]    OFF
 DO[ 2002]    OFF
 DO[ 2003]    OFF
 DO[ 2004]    OFF
 DO[ 2005]    OFF
 DO[ 2006]    OFF
 DO[ 2007]    OFF
 DO[ 2008]    OFF
 DO[ 2009]    OFF
 DO[ 2010]    OFF
 DO[ 2011]    OFF
 DO[ 2012]    OFF
 DO[ 2013]    OFF
 DO[ 2014]    OFF
 DO[ 2015]    OFF
 DO[ 2016]    OFF
 DO[ 2017]    OFF
 DO[ 2018]    OFF
 DO[ 2019]    OFF
 DO[ 2020]    OFF
 DO[ 2021]    OFF
 DO[ 2022]    OFF
 DO[ 2023]    OFF
 DO[ 2024]    OFF
 DO[ 2025]    OFF
 DO[ 2026]    OFF
 DO[ 2027]    OFF
 DO[ 2028]    OFF
 DO[ 2029]    OFF
 DO[ 2030]    OFF
 DO[ 2031]    OFF
 DO[ 2032]    OFF
 DO[ 2033]    OFF
 DO[ 2034]    OFF
 DO[ 2035]    OFF
 DO[ 2036]    OFF
 DO[ 2037]    OFF
 DO[ 2038]    OFF
 DO[ 2039]    OFF
 DO[ 2040]    OFF
 DO[ 2041]    OFF
 DO[ 2042]    OFF
 DO[ 2043]    OFF
 DO[ 2044]    OFF
 DO[ 2045]    OFF
 DO[ 2046]    OFF
 DO[ 2047]    OFF
 DO[ 2048]    OFF
 DO[   65]    OFF
 DO[   66]    OFF
 DO[   67]    OFF
 DO[   68]    OFF
 DO[   69]    OFF
 DO[   70]    OFF
 DO[   71]    OFF
 DO[   72]    OFF
 DO[   73]    OFF
 DO[   74]    OFF
 DO[   75]    OFF
 DO[   76]    OFF
 DO[   77]    OFF
 DO[   78]    OFF
 DO[   79]    OFF
 DO[   80]    OFF
 DO[   81]    OFF
 DO[   82]    OFF
 DO[   83]    OFF
 DO[   84]    OFF
 DO[   85]    OFF
 DO[   86]    OFF
 DO[   87]    OFF
 DO[   88]    OFF
 DO[   89]    OFF
 DO[   90]    OFF
 DO[   91]    OFF
 DO[   92]    OFF
 DO[   93]    OFF
 DO[   94]    OFF
 DO[   95]    OFF
 DO[   96]    OFF
 DO[   97]    OFF
 DO[   98]    OFF
 DO[   99]    OFF
 DO[  100]    OFF
 DO[  101]    OFF
 DO[  102]    OFF
 DO[  103]    OFF
 DO[  104]    OFF
 DO[  105]    OFF
 DO[  106]    OFF
 DO[  107]    OFF
 DO[  108]    OFF
 DO[  109]    OFF
 DO[  110]    OFF
 DO[  111]    OFF
 DO[  112]    OFF
 DO[  113]    OFF
 DO[  114]    OFF
 DO[  115]    OFF
 DO[  116]    OFF
Tick:   14600
TB:     1290220527
31-AUG-26 12:32 :50
========================================
 DO[ 1845]    OFF
 DO[ 1846]    OFF
 DO[ 1847]    OFF
 DO[ 1848]    OFF
 DO[ 1849]    OFF
 DO[ 1850]    OFF
 DO[ 1851]    OFF
 DO[ 1852]    OFF
 DO[ 1853]    OFF
 DO[ 1854]    OFF
 DO[ 1855]    OFF
 DO[ 1856]    OFF
 DO[ 1857]    OFF
 DO[ 1858]    OFF
 DO[ 1859]    OFF
 DO[ 1860]    OFF
 DO[ 1861]    OFF
 DO[ 1862]    OFF
 DO[ 1863]    OFF
 DO[ 1864]    OFF
 DO[ 1865]    OFF
 DO[ 1866]    OFF
 DO[ 1867]    OFF
 DO[ 1868]    OFF
 DO[ 1869]    OFF
 DO[ 1870]    OFF
 DO[ 1871]    OFF
 DO[ 1872]    OFF
 DO[ 1873]    OFF
 DO[ 1874]    OFF
 DO[ 1875]    OFF
 DO[ 1876]    OFF
 DO[ 1877]    OFF
 DO[ 1878]    OFF
 DO[ 1879]    OFF
 DO[ 1880]    OFF
 DO[ 1881]    OFF
 DO[ 1882]    OFF
 DO[ 1883]    OFF
 DO[ 1884]    OFF
 DO[ 1885]    OFF
 DO[ 1886]    OFF
 DO[ 1887]    OFF
 DO[ 1888]    OFF
 DO[ 1889]    OFF
 DO[ 1890]    OFF
 DO[ 1891]    OFF
 DO[ 1892]    OFF
 DO[ 1893]    OFF
 DO[ 1894]    OFF
 DO[ 1895]    OFF
 DO[ 1896]    OFF
 DO[ 1897]    OFF
 DO[ 1898]    OFF
 DO[ 1899]    OFF
 DO[ 1900]    OFF
 DO[ 1901]    OFF
 DO[ 1902]    OFF
 DO[ 1903]    OFF
 DO[ 1904]    OFF
 DO[ 1905]    OFF
 DO[ 1906]    OFF
 DO[ 1907]    OFF
 DO[ 1908]    OFF
 DO[ 1909]    OFF
 DO[ 1910]    OFF
 DO[ 1911]    OFF
 DO[ 1912]    OFF
 DO[ 1913]    OFF
 DO[ 1914]    OFF
 DO[ 1915]    OFF
 DO[ 1916]    OFF
 DO[ 1917]    OFF
 DO[ 1918]    OFF
 DO[ 1919]    OFF
 DO[ 1920]    OFF
 DO[ 1921]    OFF
 DO[ 1922]    OFF
 DO[ 1923]    OFF
 DO[ 1924]    OFF
 DO[ 1925]    OFF
 DO[ 1926]    OFF
 DO[ 1927]    OFF
 DO[ 1928]    OFF
 DO[ 1929]    OFF
 DO[ 1930]    OFF
 DO[ 1931]    OFF
 DO[ 1932]    OFF
 DO[ 1933]    OFF
 DO[ 1934]    OFF
 DO[ 1935]    OFF
 DO[ 1936]    OFF
 DO[ 1937]    OFF
 DO[ 1938]    OFF
 DO[ 1939]    OFF
 DO[ 1940]    OFF
 DO[ 1941]    OFF
 DO[ 1942]    OFF
 DO[ 1943]    OFF
 DO[ 1944]    OFF
 DO[ 1945]    OFF
 DO[ 1946]    OFF
 DO[ 1947]    OFF
 DO[ 1948]    OFF
 DO[ 1949]    OFF
 DO[ 1950]    OFF
 DO[ 1951]    OFF
 DO[ 1952]    OFF
 DO[ 1953]    OFF
 DO[ 1954]    OFF
 DO[ 1955]    OFF
 DO[ 1956]    OFF
 DO[ 1957]    OFF
 DO[ 1958]    OFF
 DO[ 1959]    OFF
 DO[ 1960]    OFF
 DO[ 1961]    OFF
 DO[ 1962]    OFF
 DO[ 1963]    OFF
 DO[ 1964]    OFF
 DO[ 1965]    OFF
 DO[ 1966]    OFF
 DO[ 1967]    OFF
 DO[ 1968]    OFF
 DO[ 1969]    OFF
 DO[ 1970]    OFF
 DO[ 1971]    OFF
 DO[ 1972]    OFF
Tick:   14599
TB:     1290153848
31-AUG-26 12:32 :50
========================================
 DO[ 1717]    OFF
 DO[ 1718]    OFF
 DO[ 1719]    OFF
 DO[ 1720]    OFF
 DO[ 1721]    OFF
 DO[ 1722]    OFF
 DO[ 1723]    OFF
 DO[ 1724]    OFF
 DO[ 1725]    OFF
 DO[ 1726]    OFF
 DO[ 1727]    OFF
 DO[ 1728]    OFF
 DO[ 1729]    OFF
 DO[ 1730]    OFF
 DO[ 1731]    OFF
 DO[ 1732]    OFF
 DO[ 1733]    OFF
 DO[ 1734]    OFF
 DO[ 1735]    OFF
 DO[ 1736]    OFF
 DO[ 1737]    OFF
 DO[ 1738]    OFF
 DO[ 1739]    OFF
 DO[ 1740]    OFF
 DO[ 1741]    OFF
 DO[ 1742]    OFF
 DO[ 1743]    OFF
 DO[ 1744]    OFF
 DO[ 1745]    OFF
 DO[ 1746]    OFF
 DO[ 1747]    OFF
 DO[ 1748]    OFF
 DO[ 1749]    OFF
 DO[ 1750]    OFF
 DO[ 1751]    OFF
 DO[ 1752]    OFF
 DO[ 1753]    OFF
 DO[ 1754]    OFF
 DO[ 1755]    OFF
 DO[ 1756]    OFF
 DO[ 1757]    OFF
 DO[ 1758]    OFF
 DO[ 1759]    OFF
 DO[ 1760]    OFF
 DO[ 1761]    OFF
 DO[ 1762]    OFF
 DO[ 1763]    OFF
 DO[ 1764]    OFF
 DO[ 1765]    OFF
 DO[ 1766]    OFF
 DO[ 1767]    OFF
 DO[ 1768]    OFF
 DO[ 1769]    OFF
 DO[ 1770]    OFF
 DO[ 1771]    OFF
 DO[ 1772]    OFF
 DO[ 1773]    OFF
 DO[ 1774]    OFF
 DO[ 1775]    OFF
 DO[ 1776]    OFF
 DO[ 1777]    OFF
 DO[ 1778]    OFF
 DO[ 1779]    OFF
 DO[ 1780]    OFF
 DO[ 1781]    OFF
 DO[ 1782]    OFF
 DO[ 1783]    OFF
 DO[ 1784]    OFF
 DO[ 1785]    OFF
 DO[ 1786]    OFF
 DO[ 1787]    OFF
 DO[ 1788]    OFF
 DO[ 1789]    OFF
 DO[ 1790]    OFF
 DO[ 1791]    OFF
 DO[ 1792]    OFF
 DO[ 1793]    OFF
 DO[ 1794]    OFF
 DO[ 1795]    OFF
 DO[ 1796]    OFF
 DO[ 1797]    OFF
 DO[ 1798]    OFF
 DO[ 1799]    OFF
 DO[ 1800]    OFF
 DO[ 1801]    OFF
 DO[ 1802]    OFF
 DO[ 1803]    OFF
 DO[ 1804]    OFF
 DO[ 1805]    OFF
 DO[ 1806]    OFF
 DO[ 1807]    OFF
 DO[ 1808]    OFF
 DO[ 1809]    OFF
 DO[ 1810]    OFF
 DO[ 1811]    OFF
 DO[ 1812]    OFF
 DO[ 1813]    OFF
 DO[ 1814]    OFF
 DO[ 1815]    OFF
 DO[ 1816]    OFF
 DO[ 1817]    OFF
 DO[ 1818]    OFF
 DO[ 1819]    OFF
 DO[ 1820]    OFF
 DO[ 1821]    OFF
 DO[ 1822]    OFF
 DO[ 1823]    OFF
 DO[ 1824]    OFF
 DO[ 1825]    OFF
 DO[ 1826]    OFF
 DO[ 1827]    OFF
 DO[ 1828]    OFF
 DO[ 1829]    OFF
 DO[ 1830]    OFF
 DO[ 1831]    OFF
 DO[ 1832]    OFF
 DO[ 1833]    OFF
 DO[ 1834]    OFF
 DO[ 1835]    OFF
 DO[ 1836]    OFF
 DO[ 1837]    OFF
 DO[ 1838]    OFF
 DO[ 1839]    OFF
 DO[ 1840]    OFF
 DO[ 1841]    OFF
 DO[ 1842]    OFF
 DO[ 1843]    OFF
 DO[ 1844]    OFF
Tick:   14598
TB:     1290087236
31-AUG-26 12:32 :50
========================================
 DO[ 1589]    OFF
 DO[ 1590]    OFF
 DO[ 1591]    OFF
 DO[ 1592]    OFF
 DO[ 1593]    OFF
 DO[ 1594]    OFF
 DO[ 1595]    OFF
 DO[ 1596]    OFF
 DO[ 1597]    OFF
 DO[ 1598]    OFF
 DO[ 1599]    OFF
 DO[ 1600]    OFF
 DO[ 1601]    OFF
 DO[ 1602]    OFF
 DO[ 1603]    OFF
 DO[ 1604]    OFF
 DO[ 1605]    OFF
 DO[ 1606]    OFF
 DO[ 1607]    OFF
 DO[ 1608]    OFF
 DO[ 1609]    OFF
 DO[ 1610]    OFF
 DO[ 1611]    OFF
 DO[ 1612]    OFF
 DO[ 1613]    OFF
 DO[ 1614]    OFF
 DO[ 1615]    OFF
 DO[ 1616]    OFF
 DO[ 1617]    OFF
 DO[ 1618]    OFF
 DO[ 1619]    OFF
 DO[ 1620]    OFF
 DO[ 1621]    OFF
 DO[ 1622]    OFF
 DO[ 1623]    OFF
 DO[ 1624]    OFF
 DO[ 1625]    OFF
 DO[ 1626]    OFF
 DO[ 1627]    OFF
 DO[ 1628]    OFF
 DO[ 1629]    OFF
 DO[ 1630]    OFF
 DO[ 1631]    OFF
 DO[ 1632]    OFF
 DO[ 1633]    OFF
 DO[ 1634]    OFF
 DO[ 1635]    OFF
 DO[ 1636]    OFF
 DO[ 1637]    OFF
 DO[ 1638]    OFF
 DO[ 1639]    OFF
 DO[ 1640]    OFF
 DO[ 1641]    OFF
 DO[ 1642]    OFF
 DO[ 1643]    OFF
 DO[ 1644]    OFF
 DO[ 1645]    OFF
 DO[ 1646]    OFF
 DO[ 1647]    OFF
 DO[ 1648]    OFF
 DO[ 1649]    OFF
 DO[ 1650]    OFF
 DO[ 1651]    OFF
 DO[ 1652]    OFF
 DO[ 1653]    OFF
 DO[ 1654]    OFF
 DO[ 1655]    OFF
 DO[ 1656]    OFF
 DO[ 1657]    OFF
 DO[ 1658]    OFF
 DO[ 1659]    OFF
 DO[ 1660]    OFF
 DO[ 1661]    OFF
 DO[ 1662]    OFF
 DO[ 1663]    OFF
 DO[ 1664]    OFF
 DO[ 1665]    OFF
 DO[ 1666]    OFF
 DO[ 1667]    OFF
 DO[ 1668]    OFF
 DO[ 1669]    OFF
 DO[ 1670]    OFF
 DO[ 1671]    OFF
 DO[ 1672]    OFF
 DO[ 1673]    OFF
 DO[ 1674]    OFF
 DO[ 1675]    OFF
 DO[ 1676]    OFF
 DO[ 1677]    OFF
 DO[ 1678]    OFF
 DO[ 1679]    OFF
 DO[ 1680]    OFF
 DO[ 1681]    OFF
 DO[ 1682]    OFF
 DO[ 1683]    OFF
 DO[ 1684]    OFF
 DO[ 1685]    OFF
 DO[ 1686]    OFF
 DO[ 1687]    OFF
 DO[ 1688]    OFF
 DO[ 1689]    OFF
 DO[ 1690]    OFF
 DO[ 1691]    OFF
 DO[ 1692]    OFF
 DO[ 1693]    OFF
 DO[ 1694]    OFF
 DO[ 1695]    OFF
 DO[ 1696]    OFF
 DO[ 1697]    OFF
 DO[ 1698]    OFF
 DO[ 1699]    OFF
 DO[ 1700]    OFF
 DO[ 1701]    OFF
 DO[ 1702]    OFF
 DO[ 1703]    OFF
 DO[ 1704]    OFF
 DO[ 1705]    OFF
 DO[ 1706]    OFF
 DO[ 1707]    OFF
 DO[ 1708]    OFF
 DO[ 1709]    OFF
 DO[ 1710]    OFF
 DO[ 1711]    OFF
 DO[ 1712]    OFF
 DO[ 1713]    OFF
 DO[ 1714]    OFF
 DO[ 1715]    OFF
 DO[ 1716]    OFF
Tick:   14597
TB:     1290020875
31-AUG-26 12:32 :50
========================================
 DO[ 1461]    OFF
 DO[ 1462]    OFF
 DO[ 1463]    OFF
 DO[ 1464]    OFF
 DO[ 1465]    OFF
 DO[ 1466]    OFF
 DO[ 1467]    OFF
 DO[ 1468]    OFF
 DO[ 1469]    OFF
 DO[ 1470]    OFF
 DO[ 1471]    OFF
 DO[ 1472]    OFF
 DO[ 1473]    OFF
 DO[ 1474]    OFF
 DO[ 1475]    OFF
 DO[ 1476]    OFF
 DO[ 1477]    OFF
 DO[ 1478]    OFF
 DO[ 1479]    OFF
 DO[ 1480]    OFF
 DO[ 1481]    OFF
 DO[ 1482]    OFF
 DO[ 1483]    OFF
 DO[ 1484]    OFF
 DO[ 1485]    OFF
 DO[ 1486]    OFF
 DO[ 1487]    OFF
 DO[ 1488]    OFF
 DO[ 1489]    OFF
 DO[ 1490]    OFF
 DO[ 1491]    OFF
 DO[ 1492]    OFF
 DO[ 1493]    OFF
 DO[ 1494]    OFF
 DO[ 1495]    OFF
 DO[ 1496]    OFF
 DO[ 1497]    OFF
 DO[ 1498]    OFF
 DO[ 1499]    OFF
 DO[ 1500]    OFF
 DO[ 1501]    OFF
 DO[ 1502]    OFF
 DO[ 1503]    OFF
 DO[ 1504]    OFF
 DO[ 1505]    OFF
 DO[ 1506]    OFF
 DO[ 1507]    OFF
 DO[ 1508]    OFF
 DO[ 1509]    OFF
 DO[ 1510]    OFF
 DO[ 1511]    OFF
 DO[ 1512]    OFF
 DO[ 1513]    OFF
 DO[ 1514]    OFF
 DO[ 1515]    OFF
 DO[ 1516]    OFF
 DO[ 1517]    OFF
 DO[ 1518]    OFF
 DO[ 1519]    OFF
 DO[ 1520]    OFF
 DO[ 1521]    OFF
 DO[ 1522]    OFF
 DO[ 1523]    OFF
 DO[ 1524]    OFF
 DO[ 1525]    OFF
 DO[ 1526]    OFF
 DO[ 1527]    OFF
 DO[ 1528]    OFF
 DO[ 1529]    OFF
 DO[ 1530]    OFF
 DO[ 1531]    OFF
 DO[ 1532]    OFF
 DO[ 1533]    OFF
 DO[ 1534]    OFF
 DO[ 1535]    OFF
 DO[ 1536]    OFF
 DO[ 1537]    OFF
 DO[ 1538]    OFF
 DO[ 1539]    OFF
 DO[ 1540]    OFF
 DO[ 1541]    OFF
 DO[ 1542]    OFF
 DO[ 1543]    OFF
 DO[ 1544]    OFF
 DO[ 1545]    OFF
 DO[ 1546]    OFF
 DO[ 1547]    OFF
 DO[ 1548]    OFF
 DO[ 1549]    OFF
 DO[ 1550]    OFF
 DO[ 1551]    OFF
 DO[ 1552]    OFF
 DO[ 1553]    OFF
 DO[ 1554]    OFF
 DO[ 1555]    OFF
 DO[ 1556]    OFF
 DO[ 1557]    OFF
 DO[ 1558]    OFF
 DO[ 1559]    OFF
 DO[ 1560]    OFF
 DO[ 1561]    OFF
 DO[ 1562]    OFF
 DO[ 1563]    OFF
 DO[ 1564]    OFF
 DO[ 1565]    OFF
 DO[ 1566]    OFF
 DO[ 1567]    OFF
 DO[ 1568]    OFF
 DO[ 1569]    OFF
 DO[ 1570]    OFF
 DO[ 1571]    OFF
 DO[ 1572]    OFF
 DO[ 1573]    OFF
 DO[ 1574]    OFF
 DO[ 1575]    OFF
 DO[ 1576]    OFF
 DO[ 1577]    OFF
 DO[ 1578]    OFF
 DO[ 1579]    OFF
 DO[ 1580]    OFF
 DO[ 1581]    OFF
 DO[ 1582]    OFF
 DO[ 1583]    OFF
 DO[ 1584]    OFF
 DO[ 1585]    OFF
 DO[ 1586]    OFF
 DO[ 1587]    OFF
 DO[ 1588]    OFF
Tick:   14596
TB:     1289953908
31-AUG-26 12:32 :50
========================================
 DO[ 1333]    OFF
 DO[ 1334]    OFF
 DO[ 1335]    OFF
 DO[ 1336]    OFF
 DO[ 1337]    OFF
 DO[ 1338]    OFF
 DO[ 1339]    OFF
 DO[ 1340]    OFF
 DO[ 1341]    OFF
 DO[ 1342]    OFF
 DO[ 1343]    OFF
 DO[ 1344]    OFF
 DO[ 1345]    OFF
 DO[ 1346]    OFF
 DO[ 1347]    OFF
 DO[ 1348]    OFF
 DO[ 1349]    OFF
 DO[ 1350]    OFF
 DO[ 1351]    OFF
 DO[ 1352]    OFF
 DO[ 1353]    OFF
 DO[ 1354]    OFF
 DO[ 1355]    OFF
 DO[ 1356]    OFF
 DO[ 1357]    OFF
 DO[ 1358]    OFF
 DO[ 1359]    OFF
 DO[ 1360]    OFF
 DO[ 1361]    OFF
 DO[ 1362]    OFF
 DO[ 1363]    OFF
 DO[ 1364]    OFF
 DO[ 1365]    OFF
 DO[ 1366]    OFF
 DO[ 1367]    OFF
 DO[ 1368]    OFF
 DO[ 1369]    OFF
 DO[ 1370]    OFF
 DO[ 1371]    OFF
 DO[ 1372]    OFF
 DO[ 1373]    OFF
 DO[ 1374]    OFF
 DO[ 1375]    OFF
 DO[ 1376]    OFF
 DO[ 1377]    OFF
 DO[ 1378]    OFF
 DO[ 1379]    OFF
 DO[ 1380]    OFF
 DO[ 1381]    OFF
 DO[ 1382]    OFF
 DO[ 1383]    OFF
 DO[ 1384]    OFF
 DO[ 1385]    OFF
 DO[ 1386]    OFF
 DO[ 1387]    OFF
 DO[ 1388]    OFF
 DO[ 1389]    OFF
 DO[ 1390]    OFF
 DO[ 1391]    OFF
 DO[ 1392]    OFF
 DO[ 1393]    OFF
 DO[ 1394]    OFF
 DO[ 1395]    OFF
 DO[ 1396]    OFF
 DO[ 1397]    OFF
 DO[ 1398]    OFF
 DO[ 1399]    OFF
 DO[ 1400]    OFF
 DO[ 1401]    OFF
 DO[ 1402]    OFF
 DO[ 1403]    OFF
 DO[ 1404]    OFF
 DO[ 1405]    OFF
 DO[ 1406]    OFF
 DO[ 1407]    OFF
 DO[ 1408]    OFF
 DO[ 1409]    OFF
 DO[ 1410]    OFF
 DO[ 1411]    OFF
 DO[ 1412]    OFF
 DO[ 1413]    OFF
 DO[ 1414]    OFF
 DO[ 1415]    OFF
 DO[ 1416]    OFF
 DO[ 1417]    OFF
 DO[ 1418]    OFF
 DO[ 1419]    OFF
 DO[ 1420]    OFF
 DO[ 1421]    OFF
 DO[ 1422]    OFF
 DO[ 1423]    OFF
 DO[ 1424]    OFF
 DO[ 1425]    OFF
 DO[ 1426]    OFF
 DO[ 1427]    OFF
 DO[ 1428]    OFF
 DO[ 1429]    OFF
 DO[ 1430]    OFF
 DO[ 1431]    OFF
 DO[ 1432]    OFF
 DO[ 1433]    OFF
 DO[ 1434]    OFF
 DO[ 1435]    OFF
 DO[ 1436]    OFF
 DO[ 1437]    OFF
 DO[ 1438]    OFF
 DO[ 1439]    OFF
 DO[ 1440]    OFF
 DO[ 1441]    OFF
 DO[ 1442]    OFF
 DO[ 1443]    OFF
 DO[ 1444]    OFF
 DO[ 1445]    OFF
 DO[ 1446]    OFF
 DO[ 1447]    OFF
 DO[ 1448]    OFF
 DO[ 1449]    OFF
 DO[ 1450]    OFF
 DO[ 1451]    OFF
 DO[ 1452]    OFF
 DO[ 1453]    OFF
 DO[ 1454]    OFF
 DO[ 1455]    OFF
 DO[ 1456]    OFF
 DO[ 1457]    OFF
 DO[ 1458]    OFF
 DO[ 1459]    OFF
 DO[ 1460]    OFF
Tick:   14595
TB:     1289887196
31-AUG-26 12:32 :50
========================================
 DO[ 1205]    OFF
 DO[ 1206]    OFF
 DO[ 1207]    OFF
 DO[ 1208]    OFF
 DO[ 1209]    OFF
 DO[ 1210]    OFF
 DO[ 1211]    OFF
 DO[ 1212]    OFF
 DO[ 1213]    OFF
 DO[ 1214]    OFF
 DO[ 1215]    OFF
 DO[ 1216]    OFF
 DO[ 1217]    OFF
 DO[ 1218]    OFF
 DO[ 1219]    OFF
 DO[ 1220]    OFF
 DO[ 1221]    OFF
 DO[ 1222]    OFF
 DO[ 1223]    OFF
 DO[ 1224]    OFF
 DO[ 1225]    OFF
 DO[ 1226]    OFF
 DO[ 1227]    OFF
 DO[ 1228]    OFF
 DO[ 1229]    OFF
 DO[ 1230]    OFF
 DO[ 1231]    OFF
 DO[ 1232]    OFF
 DO[ 1233]    OFF
 DO[ 1234]    OFF
 DO[ 1235]    OFF
 DO[ 1236]    OFF
 DO[ 1237]    OFF
 DO[ 1238]    OFF
 DO[ 1239]    OFF
 DO[ 1240]    OFF
 DO[ 1241]    OFF
 DO[ 1242]    OFF
 DO[ 1243]    OFF
 DO[ 1244]    OFF
 DO[ 1245]    OFF
 DO[ 1246]    OFF
 DO[ 1247]    OFF
 DO[ 1248]    OFF
 DO[ 1249]    OFF
 DO[ 1250]    OFF
 DO[ 1251]    OFF
 DO[ 1252]    OFF
 DO[ 1253]    OFF
 DO[ 1254]    OFF
 DO[ 1255]    OFF
 DO[ 1256]    OFF
 DO[ 1257]    OFF
 DO[ 1258]    OFF
 DO[ 1259]    OFF
 DO[ 1260]    OFF
 DO[ 1261]    OFF
 DO[ 1262]    OFF
 DO[ 1263]    OFF
 DO[ 1264]    OFF
 DO[ 1265]    OFF
 DO[ 1266]    OFF
 DO[ 1267]    OFF
 DO[ 1268]    OFF
 DO[ 1269]    OFF
 DO[ 1270]    OFF
 DO[ 1271]    OFF
 DO[ 1272]    OFF
 DO[ 1273]    OFF
 DO[ 1274]    OFF
 DO[ 1275]    OFF
 DO[ 1276]    OFF
 DO[ 1277]    OFF
 DO[ 1278]    OFF
 DO[ 1279]    OFF
 DO[ 1280]    OFF
 DO[ 1281]    OFF
 DO[ 1282]    OFF
 DO[ 1283]    OFF
 DO[ 1284]    OFF
 DO[ 1285]    OFF
 DO[ 1286]    OFF
 DO[ 1287]    OFF
 DO[ 1288]    OFF
 DO[ 1289]    OFF
 DO[ 1290]    OFF
 DO[ 1291]    OFF
 DO[ 1292]    OFF
 DO[ 1293]    OFF
 DO[ 1294]    OFF
 DO[ 1295]    OFF
 DO[ 1296]    OFF
 DO[ 1297]    OFF
 DO[ 1298]    OFF
 DO[ 1299]    OFF
 DO[ 1300]    OFF
 DO[ 1301]    OFF
 DO[ 1302]    OFF
 DO[ 1303]    OFF
 DO[ 1304]    OFF
 DO[ 1305]    OFF
 DO[ 1306]    OFF
 DO[ 1307]    OFF
 DO[ 1308]    OFF
 DO[ 1309]    OFF
 DO[ 1310]    OFF
 DO[ 1311]    OFF
 DO[ 1312]    OFF
 DO[ 1313]    OFF
 DO[ 1314]    OFF
 DO[ 1315]    OFF
 DO[ 1316]    OFF
 DO[ 1317]    OFF
 DO[ 1318]    OFF
 DO[ 1319]    OFF
 DO[ 1320]    OFF
 DO[ 1321]    OFF
 DO[ 1322]    OFF
 DO[ 1323]    OFF
 DO[ 1324]    OFF
 DO[ 1325]    OFF
 DO[ 1326]    OFF
 DO[ 1327]    OFF
 DO[ 1328]    OFF
 DO[ 1329]    OFF
 DO[ 1330]    OFF
 DO[ 1331]    OFF
 DO[ 1332]    OFF
Tick:   14594
TB:     1289820573
31-AUG-26 12:32 :50
========================================
 DI[  127]    OFF
 DI[  128]    OFF
 DI[  129]    OFF
 DI[  130]    OFF
 DI[  131]    OFF
 DI[  132]    OFF
 DI[  133]    OFF
 DI[  134]    OFF
 DO[  129]    OFF
 DO[  130]    OFF
 DO[  131]    OFF
 DO[  132]    OFF
 DO[  133]    OFF
 DO[  134]    OFF
 DO[  135]    OFF
 DO[  136]    OFF
 DO[  137]    OFF
 DO[  138]    OFF
 DO[  139]    OFF
 DO[  140]    OFF
 DO[  141]    OFF
 DO[  142]    OFF
 DO[  143]    OFF
 DO[  144]    OFF
 DO[  145]    OFF
 DO[  146]    OFF
 DO[  147]    OFF
 DO[  148]    OFF
 DO[ 1105]    OFF
 DO[ 1106]    OFF
 DO[ 1107]    OFF
 DO[ 1108]    OFF
 DO[ 1109]    OFF
 DO[ 1110]    OFF
 DO[ 1111]    OFF
 DO[ 1112]    OFF
 DO[ 1113]    OFF
 DO[ 1114]    OFF
 DO[ 1115]    OFF
 DO[ 1116]    OFF
 DO[ 1117]    OFF
 DO[ 1118]    OFF
 DO[ 1119]    OFF
 DO[ 1120]    OFF
 DO[ 1121]    OFF
 DO[ 1122]    OFF
 DO[ 1123]    OFF
 DO[ 1124]    OFF
 DO[ 1125]    OFF
 DO[ 1126]    OFF
 DO[ 1127]    OFF
 DO[ 1128]    OFF
 DO[ 1129]    OFF
 DO[ 1130]    OFF
 DO[ 1131]    OFF
 DO[ 1132]    OFF
 DO[ 1133]    OFF
 DO[ 1134]    OFF
 DO[ 1135]    OFF
 DO[ 1136]    OFF
 DO[ 1137]    OFF
 DO[ 1138]    OFF
 DO[ 1139]    OFF
 DO[ 1140]    OFF
 DO[ 1141]    OFF
 DO[ 1142]    OFF
 DO[ 1143]    OFF
 DO[ 1144]    OFF
 DO[ 1145]    OFF
 DO[ 1146]    OFF
 DO[ 1147]    OFF
 DO[ 1148]    OFF
 DO[ 1149]    OFF
 DO[ 1150]    OFF
 DO[ 1151]    OFF
 DO[ 1152]    OFF
 DO[ 1153]    OFF
 DO[ 1154]    OFF
 DO[ 1155]    OFF
 DO[ 1156]    OFF
 DO[ 1157]    OFF
 DO[ 1158]    OFF
 DO[ 1159]    OFF
 DO[ 1160]    OFF
 DO[ 1161]    OFF
 DO[ 1162]    OFF
 DO[ 1163]    OFF
 DO[ 1164]    OFF
 DO[ 1165]    OFF
 DO[ 1166]    OFF
 DO[ 1167]    OFF
 DO[ 1168]    OFF
 DO[ 1169]    OFF
 DO[ 1170]    OFF
 DO[ 1171]    OFF
 DO[ 1172]    OFF
 DO[ 1173]    OFF
 DO[ 1174]    OFF
 DO[ 1175]    OFF
 DO[ 1176]    OFF
 DO[ 1177]    OFF
 DO[ 1178]    OFF
 DO[ 1179]    OFF
 DO[ 1180]    OFF
 DO[ 1181]    OFF
 DO[ 1182]    OFF
 DO[ 1183]    OFF
 DO[ 1184]    OFF
 DO[ 1185]    OFF
 DO[ 1186]    OFF
 DO[ 1187]    OFF
 DO[ 1188]    OFF
 DO[ 1189]    OFF
 DO[ 1190]    OFF
 DO[ 1191]    OFF
 DO[ 1192]    OFF
 DO[ 1193]    OFF
 DO[ 1194]    OFF
 DO[ 1195]    OFF
 DO[ 1196]    OFF
 DO[ 1197]    OFF
 DO[ 1198]    OFF
 DO[ 1199]    OFF
 DO[ 1200]    OFF
 DO[ 1201]    OFF
 DO[ 1202]    OFF
 DO[ 1203]    OFF
 DO[ 1204]    OFF
Tick:   14593
TB:     1289754025
31-AUG-26 12:32 :50
========================================
 DI[ 1975]    OFF
 DI[ 1976]    OFF
 DI[ 1977]    OFF
 DI[ 1978]    OFF
 DI[ 1979]    OFF
 DI[ 1980]    OFF
 DI[ 1981]    OFF
 DI[ 1982]    OFF
 DI[ 1983]    OFF
 DI[ 1984]    OFF
 DI[ 1985]    OFF
 DI[ 1986]    OFF
 DI[ 1987]    OFF
 DI[ 1988]    OFF
 DI[ 1989]    OFF
 DI[ 1990]    OFF
 DI[ 1991]    OFF
 DI[ 1992]    OFF
 DI[ 1993]    OFF
 DI[ 1994]    OFF
 DI[ 1995]    OFF
 DI[ 1996]    OFF
 DI[ 1997]    OFF
 DI[ 1998]    OFF
 DI[ 1999]    OFF
 DI[ 2000]    OFF
 DI[ 2001]    OFF
 DI[ 2002]    OFF
 DI[ 2003]    OFF
 DI[ 2004]    OFF
 DI[ 2005]    OFF
 DI[ 2006]    OFF
 DI[ 2007]    OFF
 DI[ 2008]    OFF
 DI[ 2009]    OFF
 DI[ 2010]    OFF
 DI[ 2011]    OFF
 DI[ 2012]    OFF
 DI[ 2013]    OFF
 DI[ 2014]    OFF
 DI[ 2015]    OFF
 DI[ 2016]    OFF
 DI[ 2017]    OFF
 DI[ 2018]    OFF
 DI[ 2019]    OFF
 DI[ 2020]    OFF
 DI[ 2021]    OFF
 DI[ 2022]    OFF
 DI[ 2023]    OFF
 DI[ 2024]    OFF
 DI[ 2025]    OFF
 DI[ 2026]    OFF
 DI[ 2027]    OFF
 DI[ 2028]    OFF
 DI[ 2029]    OFF
 DI[ 2030]    OFF
 DI[ 2031]    OFF
 DI[ 2032]    OFF
 DI[ 2033]    OFF
 DI[ 2034]    OFF
 DI[ 2035]    OFF
 DI[ 2036]    OFF
 DI[ 2037]    OFF
 DI[ 2038]    OFF
 DI[ 2039]    OFF
 DI[ 2040]    OFF
 DI[ 2041]    OFF
 DI[ 2042]    OFF
 DI[ 2043]    OFF
 DI[ 2044]    OFF
 DI[ 2045]    OFF
 DI[ 2046]    OFF
 DI[ 2047]    OFF
 DI[ 2048]    OFF
 DI[   73]    OFF
 DI[   74]    OFF
 DI[   75]    OFF
 DI[   76]    OFF
 DI[   77]    OFF
 DI[   78]    OFF
 DI[   79]    OFF
 DI[   80]    OFF
 DI[   81]    OFF
 DI[   82]    OFF
 DI[   83]    OFF
 DI[   84]    OFF
 DI[   85]    OFF
 DI[   86]    OFF
 DI[   87]    OFF
 DI[   88]    OFF
 DI[   89]    OFF
 DI[   90]    OFF
 DI[   91]    OFF
 DI[   92]    OFF
 DI[   93]    OFF
 DI[   94]    OFF
 DI[   95]    OFF
 DI[   96]    OFF
 DI[   97]    OFF
 DI[   98]    OFF
 DI[   99]    OFF
 DI[  100]    OFF
 DI[  101]    OFF
 DI[  102]    OFF
 DI[  103]    OFF
 DI[  104]    OFF
 DI[  105]    OFF
 DI[  106]    OFF
 DI[  107]    OFF
 DI[  108]    OFF
 DI[  109]    OFF
 DI[  110]    OFF
 DI[  111]    OFF
 DI[  112]    OFF
 DI[  113]    OFF
 DI[  114]    OFF
 DI[  115]    OFF
 DI[  116]    OFF
 DI[  117]    OFF
 DI[  118]    OFF
 DI[  119]    OFF
 DI[  120]    OFF
 DI[  121]    OFF
 DI[  122]    OFF
 DI[  123]    OFF
 DI[  124]    OFF
 DI[  125]    OFF
 DI[  126]    OFF
Tick:   14592
TB:     1289688310
31-AUG-26 12:32 :50
========================================
 DI[ 1847]    OFF
 DI[ 1848]    OFF
 DI[ 1849]    OFF
 DI[ 1850]    OFF
 DI[ 1851]    OFF
 DI[ 1852]    OFF
 DI[ 1853]    OFF
 DI[ 1854]    OFF
 DI[ 1855]    OFF
 DI[ 1856]    OFF
 DI[ 1857]    OFF
 DI[ 1858]    OFF
 DI[ 1859]    OFF
 DI[ 1860]    OFF
 DI[ 1861]    OFF
 DI[ 1862]    OFF
 DI[ 1863]    OFF
 DI[ 1864]    OFF
 DI[ 1865]    OFF
 DI[ 1866]    OFF
 DI[ 1867]    OFF
 DI[ 1868]    OFF
 DI[ 1869]    OFF
 DI[ 1870]    OFF
 DI[ 1871]    OFF
 DI[ 1872]    OFF
 DI[ 1873]    OFF
 DI[ 1874]    OFF
 DI[ 1875]    OFF
 DI[ 1876]    OFF
 DI[ 1877]    OFF
 DI[ 1878]    OFF
 DI[ 1879]    OFF
 DI[ 1880]    OFF
 DI[ 1881]    OFF
 DI[ 1882]    OFF
 DI[ 1883]    OFF
 DI[ 1884]    OFF
 DI[ 1885]    OFF
 DI[ 1886]    OFF
 DI[ 1887]    OFF
 DI[ 1888]    OFF
 DI[ 1889]    OFF
 DI[ 1890]    OFF
 DI[ 1891]    OFF
 DI[ 1892]    OFF
 DI[ 1893]    OFF
 DI[ 1894]    OFF
 DI[ 1895]    OFF
 DI[ 1896]    OFF
 DI[ 1897]    OFF
 DI[ 1898]    OFF
 DI[ 1899]    OFF
 DI[ 1900]    OFF
 DI[ 1901]    OFF
 DI[ 1902]    OFF
 DI[ 1903]    OFF
 DI[ 1904]    OFF
 DI[ 1905]    OFF
 DI[ 1906]    OFF
 DI[ 1907]    OFF
 DI[ 1908]    OFF
 DI[ 1909]    OFF
 DI[ 1910]    OFF
 DI[ 1911]    OFF
 DI[ 1912]    OFF
 DI[ 1913]    OFF
 DI[ 1914]    OFF
 DI[ 1915]    OFF
 DI[ 1916]    OFF
 DI[ 1917]    OFF
 DI[ 1918]    OFF
 DI[ 1919]    OFF
 DI[ 1920]    OFF
 DI[ 1921]    OFF
 DI[ 1922]    OFF
 DI[ 1923]    OFF
 DI[ 1924]    OFF
 DI[ 1925]    OFF
 DI[ 1926]    OFF
 DI[ 1927]    OFF
 DI[ 1928]    OFF
 DI[ 1929]    OFF
 DI[ 1930]    OFF
 DI[ 1931]    OFF
 DI[ 1932]    OFF
 DI[ 1933]    OFF
 DI[ 1934]    OFF
 DI[ 1935]    OFF
 DI[ 1936]    OFF
 DI[ 1937]    OFF
 DI[ 1938]    OFF
 DI[ 1939]    OFF
 DI[ 1940]    OFF
 DI[ 1941]    OFF
 DI[ 1942]    OFF
 DI[ 1943]    OFF
 DI[ 1944]    OFF
 DI[ 1945]    OFF
 DI[ 1946]    OFF
 DI[ 1947]    OFF
 DI[ 1948]    OFF
 DI[ 1949]    OFF
 DI[ 1950]    OFF
 DI[ 1951]    OFF
 DI[ 1952]    OFF
 DI[ 1953]    OFF
 DI[ 1954]    OFF
 DI[ 1955]    OFF
 DI[ 1956]    OFF
 DI[ 1957]    OFF
 DI[ 1958]    OFF
 DI[ 1959]    OFF
 DI[ 1960]    OFF
 DI[ 1961]    OFF
 DI[ 1962]    OFF
 DI[ 1963]    OFF
 DI[ 1964]    OFF
 DI[ 1965]    OFF
 DI[ 1966]    OFF
 DI[ 1967]    OFF
 DI[ 1968]    OFF
 DI[ 1969]    OFF
 DI[ 1970]    OFF
 DI[ 1971]    OFF
 DI[ 1972]    OFF
 DI[ 1973]    OFF
 DI[ 1974]    OFF
Tick:   14591
TB:     1289620641
31-AUG-26 12:32 :50
========================================
 DI[ 1719]    OFF
 DI[ 1720]    OFF
 DI[ 1721]    OFF
 DI[ 1722]    OFF
 DI[ 1723]    OFF
 DI[ 1724]    OFF
 DI[ 1725]    OFF
 DI[ 1726]    OFF
 DI[ 1727]    OFF
 DI[ 1728]    OFF
 DI[ 1729]    OFF
 DI[ 1730]    OFF
 DI[ 1731]    OFF
 DI[ 1732]    OFF
 DI[ 1733]    OFF
 DI[ 1734]    OFF
 DI[ 1735]    OFF
 DI[ 1736]    OFF
 DI[ 1737]    OFF
 DI[ 1738]    OFF
 DI[ 1739]    OFF
 DI[ 1740]    OFF
 DI[ 1741]    OFF
 DI[ 1742]    OFF
 DI[ 1743]    OFF
 DI[ 1744]    OFF
 DI[ 1745]    OFF
 DI[ 1746]    OFF
 DI[ 1747]    OFF
 DI[ 1748]    OFF
 DI[ 1749]    OFF
 DI[ 1750]    OFF
 DI[ 1751]    OFF
 DI[ 1752]    OFF
 DI[ 1753]    OFF
 DI[ 1754]    OFF
 DI[ 1755]    OFF
 DI[ 1756]    OFF
 DI[ 1757]    OFF
 DI[ 1758]    OFF
 DI[ 1759]    OFF
 DI[ 1760]    OFF
 DI[ 1761]    OFF
 DI[ 1762]    OFF
 DI[ 1763]    OFF
 DI[ 1764]    OFF
 DI[ 1765]    OFF
 DI[ 1766]    OFF
 DI[ 1767]    OFF
 DI[ 1768]    OFF
 DI[ 1769]    OFF
 DI[ 1770]    OFF
 DI[ 1771]    OFF
 DI[ 1772]    OFF
 DI[ 1773]    OFF
 DI[ 1774]    OFF
 DI[ 1775]    OFF
 DI[ 1776]    OFF
 DI[ 1777]    OFF
 DI[ 1778]    OFF
 DI[ 1779]    OFF
 DI[ 1780]    OFF
 DI[ 1781]    OFF
 DI[ 1782]    OFF
 DI[ 1783]    OFF
 DI[ 1784]    OFF
 DI[ 1785]    OFF
 DI[ 1786]    OFF
 DI[ 1787]    OFF
 DI[ 1788]    OFF
 DI[ 1789]    OFF
 DI[ 1790]    OFF
 DI[ 1791]    OFF
 DI[ 1792]    OFF
 DI[ 1793]    OFF
 DI[ 1794]    OFF
 DI[ 1795]    OFF
 DI[ 1796]    OFF
 DI[ 1797]    OFF
 DI[ 1798]    OFF
 DI[ 1799]    OFF
 DI[ 1800]    OFF
 DI[ 1801]    OFF
 DI[ 1802]    OFF
 DI[ 1803]    OFF
 DI[ 1804]    OFF
 DI[ 1805]    OFF
 DI[ 1806]    OFF
 DI[ 1807]    OFF
 DI[ 1808]    OFF
 DI[ 1809]    OFF
 DI[ 1810]    OFF
 DI[ 1811]    OFF
 DI[ 1812]    OFF
 DI[ 1813]    OFF
 DI[ 1814]    OFF
 DI[ 1815]    OFF
 DI[ 1816]    OFF
 DI[ 1817]    OFF
 DI[ 1818]    OFF
 DI[ 1819]    OFF
 DI[ 1820]    OFF
 DI[ 1821]    OFF
 DI[ 1822]    OFF
 DI[ 1823]    OFF
 DI[ 1824]    OFF
 DI[ 1825]    OFF
 DI[ 1826]    OFF
 DI[ 1827]    OFF
 DI[ 1828]    OFF
 DI[ 1829]    OFF
 DI[ 1830]    OFF
 DI[ 1831]    OFF
 DI[ 1832]    OFF
 DI[ 1833]    OFF
 DI[ 1834]    OFF
 DI[ 1835]    OFF
 DI[ 1836]    OFF
 DI[ 1837]    OFF
 DI[ 1838]    OFF
 DI[ 1839]    OFF
 DI[ 1840]    OFF
 DI[ 1841]    OFF
 DI[ 1842]    OFF
 DI[ 1843]    OFF
 DI[ 1844]    OFF
 DI[ 1845]    OFF
 DI[ 1846]    OFF
Tick:   14590
TB:     1289555009
31-AUG-26 12:32 :50
========================================
 DI[ 1591]    OFF
 DI[ 1592]    OFF
 DI[ 1593]    OFF
 DI[ 1594]    OFF
 DI[ 1595]    OFF
 DI[ 1596]    OFF
 DI[ 1597]    OFF
 DI[ 1598]    OFF
 DI[ 1599]    OFF
 DI[ 1600]    OFF
 DI[ 1601]    OFF
 DI[ 1602]    OFF
 DI[ 1603]    OFF
 DI[ 1604]    OFF
 DI[ 1605]    OFF
 DI[ 1606]    OFF
 DI[ 1607]    OFF
 DI[ 1608]    OFF
 DI[ 1609]    OFF
 DI[ 1610]    OFF
 DI[ 1611]    OFF
 DI[ 1612]    OFF
 DI[ 1613]    OFF
 DI[ 1614]    OFF
 DI[ 1615]    OFF
 DI[ 1616]    OFF
 DI[ 1617]    OFF
 DI[ 1618]    OFF
 DI[ 1619]    OFF
 DI[ 1620]    OFF
 DI[ 1621]    OFF
 DI[ 1622]    OFF
 DI[ 1623]    OFF
 DI[ 1624]    OFF
 DI[ 1625]    OFF
 DI[ 1626]    OFF
 DI[ 1627]    OFF
 DI[ 1628]    OFF
 DI[ 1629]    OFF
 DI[ 1630]    OFF
 DI[ 1631]    OFF
 DI[ 1632]    OFF
 DI[ 1633]    OFF
 DI[ 1634]    OFF
 DI[ 1635]    OFF
 DI[ 1636]    OFF
 DI[ 1637]    OFF
 DI[ 1638]    OFF
 DI[ 1639]    OFF
 DI[ 1640]    OFF
 DI[ 1641]    OFF
 DI[ 1642]    OFF
 DI[ 1643]    OFF
 DI[ 1644]    OFF
 DI[ 1645]    OFF
 DI[ 1646]    OFF
 DI[ 1647]    OFF
 DI[ 1648]    OFF
 DI[ 1649]    OFF
 DI[ 1650]    OFF
 DI[ 1651]    OFF
 DI[ 1652]    OFF
 DI[ 1653]    OFF
 DI[ 1654]    OFF
 DI[ 1655]    OFF
 DI[ 1656]    OFF
 DI[ 1657]    OFF
 DI[ 1658]    OFF
 DI[ 1659]    OFF
 DI[ 1660]    OFF
 DI[ 1661]    OFF
 DI[ 1662]    OFF
 DI[ 1663]    OFF
 DI[ 1664]    OFF
 DI[ 1665]    OFF
 DI[ 1666]    OFF
 DI[ 1667]    OFF
 DI[ 1668]    OFF
 DI[ 1669]    OFF
 DI[ 1670]    OFF
 DI[ 1671]    OFF
 DI[ 1672]    OFF
 DI[ 1673]    OFF
 DI[ 1674]    OFF
 DI[ 1675]    OFF
 DI[ 1676]    OFF
 DI[ 1677]    OFF
 DI[ 1678]    OFF
 DI[ 1679]    OFF
 DI[ 1680]    OFF
 DI[ 1681]    OFF
 DI[ 1682]    OFF
 DI[ 1683]    OFF
 DI[ 1684]    OFF
 DI[ 1685]    OFF
 DI[ 1686]    OFF
 DI[ 1687]    OFF
 DI[ 1688]    OFF
 DI[ 1689]    OFF
 DI[ 1690]    OFF
 DI[ 1691]    OFF
 DI[ 1692]    OFF
 DI[ 1693]    OFF
 DI[ 1694]    OFF
 DI[ 1695]    OFF
 DI[ 1696]    OFF
 DI[ 1697]    OFF
 DI[ 1698]    OFF
 DI[ 1699]    OFF
 DI[ 1700]    OFF
 DI[ 1701]    OFF
 DI[ 1702]    OFF
 DI[ 1703]    OFF
 DI[ 1704]    OFF
 DI[ 1705]    OFF
 DI[ 1706]    OFF
 DI[ 1707]    OFF
 DI[ 1708]    OFF
 DI[ 1709]    OFF
 DI[ 1710]    OFF
 DI[ 1711]    OFF
 DI[ 1712]    OFF
 DI[ 1713]    OFF
 DI[ 1714]    OFF
 DI[ 1715]    OFF
 DI[ 1716]    OFF
 DI[ 1717]    OFF
 DI[ 1718]    OFF
Tick:   14589
TB:     1289487512
31-AUG-26 12:32 :50
========================================
 DI[ 1463]    OFF
 DI[ 1464]    OFF
 DI[ 1465]    OFF
 DI[ 1466]    OFF
 DI[ 1467]    OFF
 DI[ 1468]    OFF
 DI[ 1469]    OFF
 DI[ 1470]    OFF
 DI[ 1471]    OFF
 DI[ 1472]    OFF
 DI[ 1473]    OFF
 DI[ 1474]    OFF
 DI[ 1475]    OFF
 DI[ 1476]    OFF
 DI[ 1477]    OFF
 DI[ 1478]    OFF
 DI[ 1479]    OFF
 DI[ 1480]    OFF
 DI[ 1481]    OFF
 DI[ 1482]    OFF
 DI[ 1483]    OFF
 DI[ 1484]    OFF
 DI[ 1485]    OFF
 DI[ 1486]    OFF
 DI[ 1487]    OFF
 DI[ 1488]    OFF
 DI[ 1489]    OFF
 DI[ 1490]    OFF
 DI[ 1491]    OFF
 DI[ 1492]    OFF
 DI[ 1493]    OFF
 DI[ 1494]    OFF
 DI[ 1495]    OFF
 DI[ 1496]    OFF
 DI[ 1497]    OFF
 DI[ 1498]    OFF
 DI[ 1499]    OFF
 DI[ 1500]    OFF
 DI[ 1501]    OFF
 DI[ 1502]    OFF
 DI[ 1503]    OFF
 DI[ 1504]    OFF
 DI[ 1505]    OFF
 DI[ 1506]    OFF
 DI[ 1507]    OFF
 DI[ 1508]    OFF
 DI[ 1509]    OFF
 DI[ 1510]    OFF
 DI[ 1511]    OFF
 DI[ 1512]    OFF
 DI[ 1513]    OFF
 DI[ 1514]    OFF
 DI[ 1515]    OFF
 DI[ 1516]    OFF
 DI[ 1517]    OFF
 DI[ 1518]    OFF
 DI[ 1519]    OFF
 DI[ 1520]    OFF
 DI[ 1521]    OFF
 DI[ 1522]    OFF
 DI[ 1523]    OFF
 DI[ 1524]    OFF
 DI[ 1525]    OFF
 DI[ 1526]    OFF
 DI[ 1527]    OFF
 DI[ 1528]    OFF
 DI[ 1529]    OFF
 DI[ 1530]    OFF
 DI[ 1531]    OFF
 DI[ 1532]    OFF
 DI[ 1533]    OFF
 DI[ 1534]    OFF
 DI[ 1535]    OFF
 DI[ 1536]    OFF
 DI[ 1537]    OFF
 DI[ 1538]    OFF
 DI[ 1539]    OFF
 DI[ 1540]    OFF
 DI[ 1541]    OFF
 DI[ 1542]    OFF
 DI[ 1543]    OFF
 DI[ 1544]    OFF
 DI[ 1545]    OFF
 DI[ 1546]    OFF
 DI[ 1547]    OFF
 DI[ 1548]    OFF
 DI[ 1549]    OFF
 DI[ 1550]    OFF
 DI[ 1551]    OFF
 DI[ 1552]    OFF
 DI[ 1553]    OFF
 DI[ 1554]    OFF
 DI[ 1555]    OFF
 DI[ 1556]    OFF
 DI[ 1557]    OFF
 DI[ 1558]    OFF
 DI[ 1559]    OFF
 DI[ 1560]    OFF
 DI[ 1561]    OFF
 DI[ 1562]    OFF
 DI[ 1563]    OFF
 DI[ 1564]    OFF
 DI[ 1565]    OFF
 DI[ 1566]    OFF
 DI[ 1567]    OFF
 DI[ 1568]    OFF
 DI[ 1569]    OFF
 DI[ 1570]    OFF
 DI[ 1571]    OFF
 DI[ 1572]    OFF
 DI[ 1573]    OFF
 DI[ 1574]    OFF
 DI[ 1575]    OFF
 DI[ 1576]    OFF
 DI[ 1577]    OFF
 DI[ 1578]    OFF
 DI[ 1579]    OFF
 DI[ 1580]    OFF
 DI[ 1581]    OFF
 DI[ 1582]    OFF
 DI[ 1583]    OFF
 DI[ 1584]    OFF
 DI[ 1585]    OFF
 DI[ 1586]    OFF
 DI[ 1587]    OFF
 DI[ 1588]    OFF
 DI[ 1589]    OFF
 DI[ 1590]    OFF
Tick:   14588
TB:     1289420550
31-AUG-26 12:32 :50
========================================
 DI[ 1335]    OFF
 DI[ 1336]    OFF
 DI[ 1337]    OFF
 DI[ 1338]    OFF
 DI[ 1339]    OFF
 DI[ 1340]    OFF
 DI[ 1341]    OFF
 DI[ 1342]    OFF
 DI[ 1343]    OFF
 DI[ 1344]    OFF
 DI[ 1345]    OFF
 DI[ 1346]    OFF
 DI[ 1347]    OFF
 DI[ 1348]    OFF
 DI[ 1349]    OFF
 DI[ 1350]    OFF
 DI[ 1351]    OFF
 DI[ 1352]    OFF
 DI[ 1353]    OFF
 DI[ 1354]    OFF
 DI[ 1355]    OFF
 DI[ 1356]    OFF
 DI[ 1357]    OFF
 DI[ 1358]    OFF
 DI[ 1359]    OFF
 DI[ 1360]    OFF
 DI[ 1361]    OFF
 DI[ 1362]    OFF
 DI[ 1363]    OFF
 DI[ 1364]    OFF
 DI[ 1365]    OFF
 DI[ 1366]    OFF
 DI[ 1367]    OFF
 DI[ 1368]    OFF
 DI[ 1369]    OFF
 DI[ 1370]    OFF
 DI[ 1371]    OFF
 DI[ 1372]    OFF
 DI[ 1373]    OFF
 DI[ 1374]    OFF
 DI[ 1375]    OFF
 DI[ 1376]    OFF
 DI[ 1377]    OFF
 DI[ 1378]    OFF
 DI[ 1379]    OFF
 DI[ 1380]    OFF
 DI[ 1381]    OFF
 DI[ 1382]    OFF
 DI[ 1383]    OFF
 DI[ 1384]    OFF
 DI[ 1385]    OFF
 DI[ 1386]    OFF
 DI[ 1387]    OFF
 DI[ 1388]    OFF
 DI[ 1389]    OFF
 DI[ 1390]    OFF
 DI[ 1391]    OFF
 DI[ 1392]    OFF
 DI[ 1393]    OFF
 DI[ 1394]    OFF
 DI[ 1395]    OFF
 DI[ 1396]    OFF
 DI[ 1397]    OFF
 DI[ 1398]    OFF
 DI[ 1399]    OFF
 DI[ 1400]    OFF
 DI[ 1401]    OFF
 DI[ 1402]    OFF
 DI[ 1403]    OFF
 DI[ 1404]    OFF
 DI[ 1405]    OFF
 DI[ 1406]    OFF
 DI[ 1407]    OFF
 DI[ 1408]    OFF
 DI[ 1409]    OFF
 DI[ 1410]    OFF
 DI[ 1411]    OFF
 DI[ 1412]    OFF
 DI[ 1413]    OFF
 DI[ 1414]    OFF
 DI[ 1415]    OFF
 DI[ 1416]    OFF
 DI[ 1417]    OFF
 DI[ 1418]    OFF
 DI[ 1419]    OFF
 DI[ 1420]    OFF
 DI[ 1421]    OFF
 DI[ 1422]    OFF
 DI[ 1423]    OFF
 DI[ 1424]    OFF
 DI[ 1425]    OFF
 DI[ 1426]    OFF
 DI[ 1427]    OFF
 DI[ 1428]    OFF
 DI[ 1429]    OFF
 DI[ 1430]    OFF
 DI[ 1431]    OFF
 DI[ 1432]    OFF
 DI[ 1433]    OFF
 DI[ 1434]    OFF
 DI[ 1435]    OFF
 DI[ 1436]    OFF
 DI[ 1437]    OFF
 DI[ 1438]    OFF
 DI[ 1439]    OFF
 DI[ 1440]    OFF
 DI[ 1441]    OFF
 DI[ 1442]    OFF
 DI[ 1443]    OFF
 DI[ 1444]    OFF
 DI[ 1445]    OFF
 DI[ 1446]    OFF
 DI[ 1447]    OFF
 DI[ 1448]    OFF
 DI[ 1449]    OFF
 DI[ 1450]    OFF
 DI[ 1451]    OFF
 DI[ 1452]    OFF
 DI[ 1453]    OFF
 DI[ 1454]    OFF
 DI[ 1455]    OFF
 DI[ 1456]    OFF
 DI[ 1457]    OFF
 DI[ 1458]    OFF
 DI[ 1459]    OFF
 DI[ 1460]    OFF
 DI[ 1461]    OFF
 DI[ 1462]    OFF
Tick:   14587
TB:     1289353879
31-AUG-26 12:32 :50
========================================
 DI[ 1207]    OFF
 DI[ 1208]    OFF
 DI[ 1209]    OFF
 DI[ 1210]    OFF
 DI[ 1211]    OFF
 DI[ 1212]    OFF
 DI[ 1213]    OFF
 DI[ 1214]    OFF
 DI[ 1215]    OFF
 DI[ 1216]    OFF
 DI[ 1217]    OFF
 DI[ 1218]    OFF
 DI[ 1219]    OFF
 DI[ 1220]    OFF
 DI[ 1221]    OFF
 DI[ 1222]    OFF
 DI[ 1223]    OFF
 DI[ 1224]    OFF
 DI[ 1225]    OFF
 DI[ 1226]    OFF
 DI[ 1227]    OFF
 DI[ 1228]    OFF
 DI[ 1229]    OFF
 DI[ 1230]    OFF
 DI[ 1231]    OFF
 DI[ 1232]    OFF
 DI[ 1233]    OFF
 DI[ 1234]    OFF
 DI[ 1235]    OFF
 DI[ 1236]    OFF
 DI[ 1237]    OFF
 DI[ 1238]    OFF
 DI[ 1239]    OFF
 DI[ 1240]    OFF
 DI[ 1241]    OFF
 DI[ 1242]    OFF
 DI[ 1243]    OFF
 DI[ 1244]    OFF
 DI[ 1245]    OFF
 DI[ 1246]    OFF
 DI[ 1247]    OFF
 DI[ 1248]    OFF
 DI[ 1249]    OFF
 DI[ 1250]    OFF
 DI[ 1251]    OFF
 DI[ 1252]    OFF
 DI[ 1253]    OFF
 DI[ 1254]    OFF
 DI[ 1255]    OFF
 DI[ 1256]    OFF
 DI[ 1257]    OFF
 DI[ 1258]    OFF
 DI[ 1259]    OFF
 DI[ 1260]    OFF
 DI[ 1261]    OFF
 DI[ 1262]    OFF
 DI[ 1263]    OFF
 DI[ 1264]    OFF
 DI[ 1265]    OFF
 DI[ 1266]    OFF
 DI[ 1267]    OFF
 DI[ 1268]    OFF
 DI[ 1269]    OFF
 DI[ 1270]    OFF
 DI[ 1271]    OFF
 DI[ 1272]    OFF
 DI[ 1273]    OFF
 DI[ 1274]    OFF
 DI[ 1275]    OFF
 DI[ 1276]    OFF
 DI[ 1277]    OFF
 DI[ 1278]    OFF
 DI[ 1279]    OFF
 DI[ 1280]    OFF
 DI[ 1281]    OFF
 DI[ 1282]    OFF
 DI[ 1283]    OFF
 DI[ 1284]    OFF
 DI[ 1285]    OFF
 DI[ 1286]    OFF
 DI[ 1287]    OFF
 DI[ 1288]    OFF
 DI[ 1289]    OFF
 DI[ 1290]    OFF
 DI[ 1291]    OFF
 DI[ 1292]    OFF
 DI[ 1293]    OFF
 DI[ 1294]    OFF
 DI[ 1295]    OFF
 DI[ 1296]    OFF
 DI[ 1297]    OFF
 DI[ 1298]    OFF
 DI[ 1299]    OFF
 DI[ 1300]    OFF
 DI[ 1301]    OFF
 DI[ 1302]    OFF
 DI[ 1303]    OFF
 DI[ 1304]    OFF
 DI[ 1305]    OFF
 DI[ 1306]    OFF
 DI[ 1307]    OFF
 DI[ 1308]    OFF
 DI[ 1309]    OFF
 DI[ 1310]    OFF
 DI[ 1311]    OFF
 DI[ 1312]    OFF
 DI[ 1313]    OFF
 DI[ 1314]    OFF
 DI[ 1315]    OFF
 DI[ 1316]    OFF
 DI[ 1317]    OFF
 DI[ 1318]    OFF
 DI[ 1319]    OFF
 DI[ 1320]    OFF
 DI[ 1321]    OFF
 DI[ 1322]    OFF
 DI[ 1323]    OFF
 DI[ 1324]    OFF
 DI[ 1325]    OFF
 DI[ 1326]    OFF
 DI[ 1327]    OFF
 DI[ 1328]    OFF
 DI[ 1329]    OFF
 DI[ 1330]    OFF
 DI[ 1331]    OFF
 DI[ 1332]    OFF
 DI[ 1333]    OFF
 DI[ 1334]    OFF
Tick:   14586
TB:     1289287280
31-AUG-26 12:32 :50
========================================
 DO[   25]    OFF
 DO[   26]    OFF
 DO[   27]    OFF
 DO[   28]    OFF
 DO[   29]    OFF
 DO[   30]    OFF
 DO[   31]    OFF
 DO[   32]    OFF
 DI[  137]    OFF
 DI[  138]    OFF
 DI[  139]    OFF
 DI[  140]    OFF
 DI[  141]    OFF
 DI[  142]    OFF
 DI[  143]    OFF
 DI[  144]    OFF
 DI[  145]    OFF
 DI[  146]    OFF
 DI[  147]    OFF
 DI[  148]    OFF
 DI[  149]    OFF
 DI[  150]    OFF
 DI[  151]    OFF
 DI[  152]    OFF
 DI[  153]    OFF
 DI[  154]    OFF
 DI[ 1105]    OFF
 DI[ 1106]    OFF
 DI[ 1107]    OFF
 DI[ 1108]    OFF
 DI[ 1109]    OFF
 DI[ 1110]    OFF
 DI[ 1111]    OFF
 DI[ 1112]    OFF
 DI[ 1113]    OFF
 DI[ 1114]    OFF
 DI[ 1115]    OFF
 DI[ 1116]    OFF
 DI[ 1117]    OFF
 DI[ 1118]    OFF
 DI[ 1119]    OFF
 DI[ 1120]    OFF
 DI[ 1121]    OFF
 DI[ 1122]    OFF
 DI[ 1123]    OFF
 DI[ 1124]    OFF
 DI[ 1125]    OFF
 DI[ 1126]    OFF
 DI[ 1127]    OFF
 DI[ 1128]    OFF
 DI[ 1129]    OFF
 DI[ 1130]    OFF
 DI[ 1131]    OFF
 DI[ 1132]    OFF
 DI[ 1133]    OFF
 DI[ 1134]    OFF
 DI[ 1135]    OFF
 DI[ 1136]    OFF
 DI[ 1137]    OFF
 DI[ 1138]    OFF
 DI[ 1139]    OFF
 DI[ 1140]    OFF
 DI[ 1141]    OFF
 DI[ 1142]    OFF
 DI[ 1143]    OFF
 DI[ 1144]    OFF
 DI[ 1145]    OFF
 DI[ 1146]    OFF
 DI[ 1147]    OFF
 DI[ 1148]    OFF
 DI[ 1149]    OFF
 DI[ 1150]    OFF
 DI[ 1151]    OFF
 DI[ 1152]    OFF
 DI[ 1153]    OFF
 DI[ 1154]    OFF
 DI[ 1155]    OFF
 DI[ 1156]    OFF
 DI[ 1157]    OFF
 DI[ 1158]    OFF
 DI[ 1159]    OFF
 DI[ 1160]    OFF
 DI[ 1161]    OFF
 DI[ 1162]    OFF
 DI[ 1163]    OFF
 DI[ 1164]    OFF
 DI[ 1165]    OFF
 DI[ 1166]    OFF
 DI[ 1167]    OFF
 DI[ 1168]    OFF
 DI[ 1169]    OFF
 DI[ 1170]    OFF
 DI[ 1171]    OFF
 DI[ 1172]    OFF
 DI[ 1173]    OFF
 DI[ 1174]    OFF
 DI[ 1175]    OFF
 DI[ 1176]    OFF
 DI[ 1177]    OFF
 DI[ 1178]    OFF
 DI[ 1179]    OFF
 DI[ 1180]    OFF
 DI[ 1181]    OFF
 DI[ 1182]    OFF
 DI[ 1183]    OFF
 DI[ 1184]    OFF
 DI[ 1185]    OFF
 DI[ 1186]    OFF
 DI[ 1187]    OFF
 DI[ 1188]    OFF
 DI[ 1189]    OFF
 DI[ 1190]    OFF
 DI[ 1191]    OFF
 DI[ 1192]    OFF
 DI[ 1193]    OFF
 DI[ 1194]    OFF
 DI[ 1195]    OFF
 DI[ 1196]    OFF
 DI[ 1197]    OFF
 DI[ 1198]    OFF
 DI[ 1199]    OFF
 DI[ 1200]    OFF
 DI[ 1201]    OFF
 DI[ 1202]    OFF
 DI[ 1203]    OFF
 DI[ 1204]    OFF
 DI[ 1205]    OFF
 DI[ 1206]    OFF
Tick:   14585
TB:     1289220733
31-AUG-26 12:32 :50
========================================
CSI[   57]    OFF
CSI[   58]    OFF
CSI[   59]    OFF
CSI[   60]    OFF
CSI[   61]    OFF
CSI[   62]    OFF
CSI[   63]    OFF
CSI[   64]    OFF
CSO[    1]    OFF
CSO[    2]    OFF
CSO[    3]    OFF
CSO[    4]    OFF
CSO[    5]    OFF
CSO[    6]    OFF
CSO[    7]    OFF
CSO[    8]    OFF
CSO[    9]    OFF
CSO[   10]    OFF
CSO[   11]    OFF
CSO[   12]    OFF
CSO[   13]    OFF
CSO[   14]    OFF
CSO[   15]    OFF
CSO[   16]    OFF
CSO[   17]    OFF
CSO[   18]    OFF
CSO[   19]    OFF
CSO[   20]    OFF
CSO[   21]    OFF
CSO[   22]    OFF
CSO[   23]    OFF
CSO[   24]    OFF
CSO[   25]    OFF
CSO[   26]    OFF
CSO[   27]    OFF
CSO[   28]    OFF
CSO[   29]    OFF
CSO[   30]    OFF
CSO[   31]    OFF
CSO[   32]    OFF
CSO[   33]    OFF
CSO[   34]    OFF
CSO[   35]    OFF
CSO[   36]    OFF
CSO[   37]    OFF
CSO[   38]    OFF
CSO[   39]    OFF
CSO[   40]    OFF
CSO[   41]    OFF
CSO[   42]    OFF
CSO[   43]    OFF
CSO[   44]    OFF
CSO[   45]    OFF
CSO[   46]    OFF
CSO[   47]    OFF
CSO[   48]    OFF
CSO[   49]    OFF
CSO[   50]    OFF
CSO[   51]    OFF
CSO[   52]    OFF
CSO[   53]    OFF
CSO[   54]    OFF
CSO[   55]    OFF
CSO[   56]    OFF
CSO[   57]    OFF
CSO[   58]    OFF
CSO[   59]    OFF
CSO[   60]    OFF
CSO[   61]    OFF
CSO[   62]    OFF
CSO[   63]    OFF
CSO[   64]    OFF
 DI[    1]    OFF
 DI[    2]    OFF
 DI[    3]    OFF
 DI[    4]    OFF
 DI[    5]    OFF
 DI[    6]    OFF
 DI[    7]    OFF
 DI[    8]    OFF
 DI[    9]    OFF
 DI[   10]    OFF
 DI[   11]    OFF
 DI[   12]    OFF
 DI[   13]    OFF
 DI[   14]    OFF
 DI[   15]    OFF
 DI[   16]    OFF
 DI[   17]    OFF
 DI[   18]    OFF
 DI[   19]    OFF
 DI[   20]    OFF
 DI[   21]    OFF
 DI[   22]    OFF
 DI[   23]    OFF
 DI[   24]    OFF
 DI[   25]    OFF
 DI[   26]    OFF
 DI[   27]    OFF
 DI[   28]    OFF
 DI[   29]    OFF
 DI[   30]    OFF
 DI[   31]    OFF
 DI[   32]    OFF
 DO[    1]    OFF
 DO[    2]    OFF
 DO[    3]    OFF
 DO[    4]    OFF
 DO[    5]    OFF
 DO[    6]    OFF
 DO[    7]    OFF
 DO[    8]    OFF
 DO[    9]    OFF
 DO[   10]    OFF
 DO[   11]    OFF
 DO[   12]    OFF
 DO[   13]    OFF
 DO[   14]    OFF
 DO[   15]    OFF
 DO[   16]    OFF
 DO[   17]    OFF
 DO[   18]    OFF
 DO[   19]    OFF
 DO[   20]    OFF
 DO[   21]    OFF
 DO[   22]    OFF
 DO[   23]    OFF
 DO[   24]    OFF
Tick:   14584
TB:     1289153720
31-AUG-26 12:32 :50
========================================
SPO[   81]    OFF
SPO[   82]    OFF
SPO[   83]    OFF
SPO[   84]    OFF
SPO[   85]    OFF
SPO[   86]    OFF
SPO[   87]    OFF
SPO[   88]    OFF
SPO[   89]    OFF
SPO[   90]    OFF
SPO[   91]    OFF
SPO[   92]    OFF
SPO[   93]    OFF
SPO[   94]    OFF
SPO[   95]    OFF
SPO[   96]    OFF
SPO[   97]    OFF
SPO[   98]    OFF
SPO[   99]    OFF
SPO[  100]    OFF
SPO[  101]    OFF
SPO[  102]    OFF
SPO[  103]    OFF
SPO[  104]    OFF
SPO[  105]    OFF
SPO[  106]    OFF
SPO[  107]    OFF
SPO[  108]    OFF
SPO[  109]    OFF
SPO[  110]    OFF
SPO[  111]    OFF
SPO[  112]    OFF
SPO[  113]    OFF
SPO[  114]    OFF
SPO[  115]    OFF
SPO[  116]    OFF
SPO[  117]    OFF
SPO[  118]    OFF
SPO[  119]    OFF
SPO[  120]    OFF
SPO[  121]    OFF
SPO[  122]    OFF
SPO[  123]    OFF
SPO[  124]    OFF
SPO[  125]    OFF
SPO[  126]    OFF
SPO[  127]    OFF
SPO[  128]    OFF
SSI[    1]    OFF
SSI[    2]    OFF
SSI[    3]    OFF
SSI[    4]    OFF
SSI[    5]    OFF
SSI[    6]    OFF
SSI[    7]    OFF
SSI[    8]    OFF
SSI[    9]    OFF
SSI[   10]    OFF
SSI[   11]    OFF
SSI[   12]    OFF
SSI[   13]    OFF
SSI[   14]    OFF
SSO[    1]    OFF
SSO[    2]    OFF
SSO[    3]    OFF
SSO[    4]    OFF
SSO[    5]    OFF
SSO[    6]    OFF
SSO[    7]    OFF
CSI[    1]    OFF
CSI[    2]    OFF
CSI[    3]    OFF
CSI[    4]    OFF
CSI[    5]    OFF
CSI[    6]    OFF
CSI[    7]    OFF
CSI[    8]    OFF
CSI[    9]    OFF
CSI[   10]    OFF
CSI[   11]    OFF
CSI[   12]    OFF
CSI[   13]    OFF
CSI[   14]    OFF
CSI[   15]    OFF
CSI[   16]    OFF
CSI[   17]    OFF
CSI[   18]    OFF
CSI[   19]    OFF
CSI[   20]    OFF
CSI[   21]    OFF
CSI[   22]    OFF
CSI[   23]    OFF
CSI[   24]    OFF
CSI[   25]    OFF
CSI[   26]    OFF
CSI[   27]    OFF
CSI[   28]    OFF
CSI[   29]    OFF
CSI[   30]    OFF
CSI[   31]    OFF
CSI[   32]    OFF
CSI[   33]    OFF
CSI[   34]    OFF
CSI[   35]    OFF
CSI[   36]    OFF
CSI[   37]    OFF
CSI[   38]    OFF
CSI[   39]    OFF
CSI[   40]    OFF
CSI[   41]    OFF
CSI[   42]    OFF
CSI[   43]    OFF
CSI[   44]    OFF
CSI[   45]    OFF
CSI[   46]    OFF
CSI[   47]    OFF
CSI[   48]    OFF
CSI[   49]    OFF
CSI[   50]    OFF
CSI[   51]    OFF
CSI[   52]    OFF
CSI[   53]    OFF
CSI[   54]    OFF
CSI[   55]    OFF
CSI[   56]    OFF
Tick:   14583
TB:     1289087126
31-AUG-26 12:32 :50
========================================
SPI[   81]    OFF
SPI[   82]    OFF
SPI[   83]    OFF
SPI[   84]    OFF
SPI[   85]    OFF
SPI[   86]    OFF
SPI[   87]    OFF
SPI[   88]    OFF
SPI[   89]    OFF
SPI[   90]    OFF
SPI[   91]    OFF
SPI[   92]    OFF
SPI[   93]    OFF
SPI[   94]    OFF
SPI[   95]    OFF
SPI[   96]    OFF
SPI[   97]    OFF
SPI[   98]    OFF
SPI[   99]    OFF
SPI[  100]    OFF
SPI[  101]    OFF
SPI[  102]    OFF
SPI[  103]    OFF
SPI[  104]    OFF
SPI[  105]    OFF
SPI[  106]    OFF
SPI[  107]    OFF
SPI[  108]    OFF
SPI[  109]    OFF
SPI[  110]    OFF
SPI[  111]    OFF
SPI[  112]    OFF
SPI[  113]    OFF
SPI[  114]    OFF
SPI[  115]    OFF
SPI[  116]    OFF
SPI[  117]    OFF
SPI[  118]    OFF
SPI[  119]    OFF
SPI[  120]    OFF
SPI[  121]    OFF
SPI[  122]    OFF
SPI[  123]    OFF
SPI[  124]    OFF
SPI[  125]    OFF
SPI[  126]    OFF
SPI[  127]    OFF
SPI[  128]    OFF
SPO[    1]    OFF
SPO[    2]    OFF
SPO[    3]    OFF
SPO[    4]    OFF
SPO[    5]    OFF
SPO[    6]    OFF
SPO[    7]    OFF
SPO[    8]    OFF
SPO[    9]    OFF
SPO[   10]    OFF
SPO[   11]    OFF
SPO[   12]    OFF
SPO[   13]    OFF
SPO[   14]    OFF
SPO[   15]    OFF
SPO[   16]    OFF
SPO[   17]    OFF
SPO[   18]    OFF
SPO[   19]    OFF
SPO[   20]    OFF
SPO[   21]    OFF
SPO[   22]    OFF
SPO[   23]    OFF
SPO[   24]    OFF
SPO[   25]    OFF
SPO[   26]    OFF
SPO[   27]    OFF
SPO[   28]    OFF
SPO[   29]    OFF
SPO[   30]    OFF
SPO[   31]    OFF
SPO[   32]    OFF
SPO[   33]    OFF
SPO[   34]    OFF
SPO[   35]    OFF
SPO[   36]    OFF
SPO[   37]    OFF
SPO[   38]    OFF
SPO[   39]    OFF
SPO[   40]    OFF
SPO[   41]    OFF
SPO[   42]    OFF
SPO[   43]    OFF
SPO[   44]    OFF
SPO[   45]    OFF
SPO[   46]    OFF
SPO[   47]    OFF
SPO[   48]    OFF
SPO[   49]    OFF
SPO[   50]    OFF
SPO[   51]    OFF
SPO[   52]    OFF
SPO[   53]    OFF
SPO[   54]    OFF
SPO[   55]    OFF
SPO[   56]    OFF
SPO[   57]    OFF
SPO[   58]    OFF
SPO[   59]    OFF
SPO[   60]    OFF
SPO[   61]    OFF
SPO[   62]    OFF
SPO[   63]    OFF
SPO[   64]    OFF
SPO[   65]    OFF
SPO[   66]    OFF
SPO[   67]    OFF
SPO[   68]    OFF
SPO[   69]    OFF
SPO[   70]    OFF
SPO[   71]    OFF
SPO[   72]    OFF
SPO[   73]    OFF
SPO[   74]    OFF
SPO[   75]    OFF
SPO[   76]    OFF
SPO[   77]    OFF
SPO[   78]    OFF
SPO[   79]    OFF
SPO[   80]    OFF
Tick:   14582
TB:     1289021536
31-AUG-26 12:32 :50
========================================
 SI[    0]    ON 
 SI[    1]    OFF
 SI[    2]    OFF
 SI[    3]    ON 
 SI[    4]    OFF
 SI[    5]    OFF
 SI[    6]    OFF
 SI[    7]    OFF
 SI[    8]    ON 
 SI[    9]    OFF
 SI[   10]    OFF
 SI[   11]    OFF
 SI[   12]    OFF
 SI[   13]    OFF
 SI[   14]    OFF
 SI[   15]    OFF
 SO[    0]    OFF
 SO[    1]    OFF
 SO[    2]    ON 
 SO[    3]    ON 
 SO[    4]    OFF
 SO[    5]    OFF
 SO[    6]    OFF
 SO[    7]    ON 
 SO[    8]    OFF
 SO[    9]    OFF
 SO[   10]    OFF
 SO[   11]    OFF
 SO[   12]    OFF
 SO[   13]    OFF
 SO[   14]    OFF
 SO[   15]    OFF
 RI[    1]    OFF
 RI[    2]    OFF
 RI[    3]    ON 
 RI[    4]    OFF
 RI[    5]    OFF
 RI[    6]    OFF
 RI[    7]    OFF
 RI[    8]    OFF
 RO[    1]    OFF
 RO[    2]    OFF
 RO[    3]    OFF
 RO[    4]    OFF
 RO[    5]    OFF
 RO[    6]    OFF
 RO[    7]    OFF
 RO[    8]    OFF
SPI[    1]    OFF
SPI[    2]    OFF
SPI[    3]    OFF
SPI[    4]    OFF
SPI[    5]    OFF
SPI[    6]    OFF
SPI[    7]    OFF
SPI[    8]    OFF
SPI[    9]    OFF
SPI[   10]    OFF
SPI[   11]    OFF
SPI[   12]    OFF
SPI[   13]    OFF
SPI[   14]    OFF
SPI[   15]    OFF
SPI[   16]    OFF
SPI[   17]    OFF
SPI[   18]    OFF
SPI[   19]    OFF
SPI[   20]    OFF
SPI[   21]    OFF
SPI[   22]    OFF
SPI[   23]    OFF
SPI[   24]    OFF
SPI[   25]    OFF
SPI[   26]    OFF
SPI[   27]    OFF
SPI[   28]    OFF
SPI[   29]    OFF
SPI[   30]    OFF
SPI[   31]    OFF
SPI[   32]    OFF
SPI[   33]    OFF
SPI[   34]    OFF
SPI[   35]    OFF
SPI[   36]    OFF
SPI[   37]    OFF
SPI[   38]    OFF
SPI[   39]    OFF
SPI[   40]    OFF
SPI[   41]    OFF
SPI[   42]    OFF
SPI[   43]    OFF
SPI[   44]    OFF
SPI[   45]    OFF
SPI[   46]    OFF
SPI[   47]    OFF
SPI[   48]    OFF
SPI[   49]    OFF
SPI[   50]    OFF
SPI[   51]    OFF
SPI[   52]    OFF
SPI[   53]    OFF
SPI[   54]    OFF
SPI[   55]    OFF
SPI[   56]    OFF
SPI[   57]    OFF
SPI[   58]    OFF
SPI[   59]    OFF
SPI[   60]    OFF
SPI[   61]    OFF
SPI[   62]    OFF
SPI[   63]    OFF
SPI[   64]    OFF
SPI[   65]    OFF
SPI[   66]    OFF
SPI[   67]    OFF
SPI[   68]    OFF
SPI[   69]    OFF
SPI[   70]    OFF
SPI[   71]    OFF
SPI[   72]    OFF
SPI[   73]    OFF
SPI[   74]    OFF
SPI[   75]    OFF
SPI[   76]    OFF
SPI[   77]    OFF
SPI[   78]    OFF
SPI[   79]    OFF
SPI[   80]    OFF
Tick:   14581
TB:     1288954309
31-AUG-26 12:32 :50
