ERRHIST.LS     Robot Name ROBOT 01-SEP-26 17:17:26  

F Number:YS04013
 VERSION: HandlingTool          
$VERSION: V9.30251       6/8/2023 
$FEATURE[1]: HandlingTool          
$FEATURE[2]: English Dictionary    
$FEATURE[3]: 4D Standard           
$FEATURE[4]: Analog I/O            
$FEATURE[5]: Angle Shift           
$FEATURE[6]: Auto Software Update  
$FEATURE[7]: Automatic Backup      
$FEATURE[8]: Background Editing    
$FEATURE[9]: Camera I/F            
$FEATURE[10]: CnrRndImp             
$FEATURE[11]: Common calib UIF      
$FEATURE[12]: Condition Monitor     
$FEATURE[13]: Control Reliable      
$FEATURE[14]: DHCP                  
$FEATURE[15]: Data Acquisition      
$FEATURE[16]: Diagnostic log        
$FEATURE[17]: Displaying License    
$FEATURE[18]: Document Viewer       
$FEATURE[19]: Dual Check Safety UIF 
$FEATURE[20]: Enhanced UIF          
$FEATURE[21]: Enhanced User Frame   
$FEATURE[22]: Ext. DIO Config       
$FEATURE[23]: Extended Error Log    
$FEATURE[24]: Extended User Frames  
$FEATURE[25]: External DI BWD       
$FEATURE[26]: FCTN Menu Save        
$FEATURE[27]: FTP Interface         
$FEATURE[28]: GigE Interface        
$FEATURE[29]: Group Mask Exchange   
$FEATURE[30]: HTTP Proxy Svr        
$FEATURE[31]: High-Speed Skip       
$FEATURE[32]: Host Communications   
$FEATURE[33]: Hour Meter            
$FEATURE[34]: I/O Interconnect 2    
$FEATURE[35]: Incr Instruction      
$FEATURE[36]: Incremental Jog       
$FEATURE[37]: KAREL Cmd. Language   
$FEATURE[38]: KAREL Run-Time Env    
$FEATURE[39]: Kernel + Basic S/W    
$FEATURE[40]: License Checker       
$FEATURE[41]: LogBook(System)       
$FEATURE[42]: MACROs, Skip/Offset   
$FEATURE[43]: MH Core               
$FEATURE[44]: MMR Motion log        
$FEATURE[45]: MechStop Protection   
$FEATURE[46]: Mirror Shift          
$FEATURE[47]: Mixed logic           
$FEATURE[48]: Mode Switch           
$FEATURE[49]: Motion Diag. Core     
$FEATURE[50]: Motion Optm. Core     
$FEATURE[51]: Motion Profiler       
$FEATURE[52]: Motion logger         
$FEATURE[53]: Multi-Tasking         
$FEATURE[54]: PCM function          
$FEATURE[55]: Position Checking     
$FEATURE[56]: Position Registers    
$FEATURE[57]: Print Function        
$FEATURE[58]: Prog Num Selection    
$FEATURE[59]: Program Adjust        
$FEATURE[60]: Program Shift         
$FEATURE[61]: Program Status        
$FEATURE[62]: Program Viewer        
$FEATURE[63]: RDM Robot Discovery   
$FEATURE[64]: Realtime Freq Anlys   
$FEATURE[65]: Remote Conn Standard  
$FEATURE[66]: Robot Servo Code      
$FEATURE[67]: SNPX basic            
$FEATURE[68]: SNTP Client           
$FEATURE[69]: Shift Library         
$FEATURE[70]: Shift and Mirror Lib  
$FEATURE[71]: Socket Messaging      
$FEATURE[72]: TCP Auto Set          
$FEATURE[73]: TCP/IP Interface      
$FEATURE[74]: TMILIB Interface      
$FEATURE[75]: TP Firmware           
$FEATURE[76]: TP Menu Accounting    
$FEATURE[77]: TPTX                  
$FEATURE[78]: Telnet Interface      
$FEATURE[79]: Tool Offset           
$FEATURE[80]: Torque Simulator I/F  
$FEATURE[81]: Touch Panel           
$FEATURE[82]: Trouble Diag. & Prev. 
$FEATURE[83]: Tutorial              
$FEATURE[84]: USB port on iPendant  
$FEATURE[85]: USR EVNT              
$FEATURE[86]: Unexcepted motn Check 
$FEATURE[87]: User Frame            
$FEATURE[88]: VCalibration Common   
$FEATURE[89]: Vision Core           
$FEATURE[90]: Vision Library        
$FEATURE[91]: Vision SP CSCX        
$FEATURE[92]: Vision SP CSGE        
$FEATURE[93]: Vision SP CSUI        
$FEATURE[94]: Web Plus              
$FEATURE[95]: Web Server            
$FEATURE[96]: Web Svr Enhancements  
$FEATURE[97]: ZDT Application       
$FEATURE[98]: ZDT EOAT Setup        
$FEATURE[99]: iPendant              
$FEATURE[100]: iPendant Grid Display 
$FEATURE[101]: iPendant Setup        
$FEATURE[102]: iRCalib. Standard     
$FEATURE[103]: iRDiag Core           
$FEATURE[104]: LR Mate 200iD         
$FEATURE[105]: Ascii Program Loader  
$FEATURE[106]: Ascii Upload          
$FEATURE[107]: CE Mark               
$FEATURE[108]: CPRUT                 
$FEATURE[109]: Constant Path         
$FEATURE[110]: Customer Reg          
$FEATURE[111]: Cycle Time Priority   
$FEATURE[112]: DCS Safe I/O connect  
$FEATURE[113]: Domain Name Serv.     
$FEATURE[114]: Ethernet/IP Scanner   
$FEATURE[115]: FRL Params            
$FEATURE[116]: HMI Device (SNPX)     
$FEATURE[117]: Internet Conn/Custo   
$FEATURE[118]: Maint Reminder Plus   
$FEATURE[119]: Maintenance Reminder  
$FEATURE[120]: PC Interface          
$FEATURE[121]: PROFINET CP16XX FW.   
$FEATURE[122]: PROFINET I/O G2       
$FEATURE[123]: PROFINET Safety       
$FEATURE[124]: Password Protection   
$FEATURE[125]: iRDiagnostics         
$FEATURE[126]: 64MB DRAM             
$FEATURE[127]: 64MB FROM             
$FEATURE[128]: Cell I/O              
$FEATURE[129]: Common shell          
$FEATURE[130]: Common shell core     
$FEATURE[131]: Common softpanel      
$FEATURE[132]: Common style select   
$FEATURE[133]: Cycle time Opt.       
$FEATURE[134]: Demo Control          
$FEATURE[135]: Disp 2nd analog port  
$FEATURE[136]: EMAIL Enhancements    
$FEATURE[137]: Email Client          
$FEATURE[138]: Enhanced Rob Serv Req 
$FEATURE[139]: Enhanced T1 Mode      
$FEATURE[140]: Ethernet/IP I/O Adp.  
$FEATURE[141]: EthernetIP I/O scan   
$FEATURE[142]: MR Standard           
$FEATURE[143]: OPC-UA                
$FEATURE[144]: OPT TP Ins            
$FEATURE[145]: PC Send Macros        
$FEATURE[146]: Real Simple Syn.(RSS) 
$FEATURE[147]: Robot Library Setup   
$FEATURE[148]: Robot Service Request 
$FEATURE[149]: SMB Client            
$FEATURE[150]: SSPC error text       
$FEATURE[151]: Space Check           
$FEATURE[152]: TCPP Extention        
$FEATURE[153]: istdpnl               
$FEATURE[154]:  SWIMEST for YS04013 

 MOTION PARAMETERS:: 
 ROBOT: LR Mate 200iD 
 SERVO ID: V11.00     
 Min Cycle: V3.00 
 Min Cart: V3.00 
GRP:  1 AXS:  1 MTR_ID biSR1/6000 20A 
                MTR_INF: H1 DSP1-S1 
                SRV_ID: P02.01
GRP:  1 AXS:  2 MTR_ID biSR1/6000 20A 
                MTR_INF: H2 DSP1-S2 
                SRV_ID: P02.01
GRP:  1 AXS:  3 MTR_ID biSR0.5/6000 20A 
                MTR_INF: H3 DSP1-S3 
                SRV_ID: P02.01
GRP:  1 AXS:  4 MTR_ID biSR0.4/6000 20A 
                MTR_INF: H4 DSP1-S4 
                SRV_ID: P02.01
GRP:  1 AXS:  5 MTR_ID biSR0.2/6000 10A 
                MTR_INF: H5 DSP1-S5 
                SRV_ID: P02.01
GRP:  1 AXS:  6 MTR_ID biSR0.2/6000 10A 
                MTR_INF: H6 DSP1-S6 
                SRV_ID: P02.01
 PWR: 33880 SRV 18535 RUN: 15070 WAIT 11703
$SCR.$NUM_GROUP  : 1
$SCR.$NUM_TOT_AXS: 6
$SCR.$MAXNUMTASK : 4
$SCR.$NUM_GROUP  : 1
$SCR.$MAXNUMUFRAM: 9
$SCR.$MAXNUMUTOOL: 10
$SCR.$NUM_GROUP  : 1
PAYLOAD          : 7

 SETUP PARAMETERS:: 
$MAXRERGNUM     : 200
$MAXPRERGNUM    : 300
HARDWARE CONFIGURATION::

         Slot  ID  FC  OP

 MEMORY INFORMATION:: 
Memory     Total      Free   Largest      Used
-----------------------------------------------
  PERM    2ee800    158914    157be0    195eec
   TPP     fa000     e587c     e542c     14784
SYSTEM    b49301       560       560    b48da1
  TEMP  2c3ffb50  259f0758  259f0758   6a0f3f8
  CMOS    300000
  DRAM  40000000
  FROM   8000000
ETHERNET CONFIGURATION::
$HOSTNAME  : ROBOT 
Router Name: ROUTER 
Hardware address :  
Subnet mask :  
Server [1]:         FTP state: 3 
Server [2]:         FTP state: 3 
